- docs/_data/navigation.yml
Fixes the side nav links in the Component vertical
Automatically generated by Netlify CMS
> Update Navigation “navigation” (fixes the side nav links in the Component vertical)

- docs/_includes/component.html
- docs/assets/css/tabs.less
[Short description explaining the high-level reason for the pull request]
- Added CSS to make design changes for small screens that @designlanguage and I decided on: 
- hide the tabs on small screens (which are styled as a links list and since we only have 2 tabs/2 sections, take up valuable screen real estate on small screens)
- hide the h6 headings that are 'inside' the tab panel area on large screens - these are only useful for small screens that don't get the tab links. this is also ok for screen readers because they get the context of the tab links on large screens and the h6 headings on small screens.
-
- Change "Contents" heading for the tabs on small screens to be more descriptive - it now says "Code snippets." also changed the heading elements to better fit the content hierarchy …
> Responsive tabs

- docs/_includes/variation-content.html
- docs/admin/config.yml
- docs/assets/css/main.less
- docs/assets/css/variation.less
Still needs CSS but I want @designlanguage to try out the admin for this when the Netlify preview URL is generated
-
-
-
1.
-
-
> HOLD: Restrictions field

- docs/admin/config.yml
will the bot do its thing/?
-
-
-
1.
-
-
> add preview-path to link directly to edited pages in netlify preview

- docs/_includes/header.html
- docs/assets/css/header.less
- docs/assets/css/variation.less
This PR is an MVP of the main nav. See hubcap/issues/292 for details.
| > 900px wide | 600 px to 900px wide | < 600px wide |
|--------------|----------------|---------|
| ![Screen Shot 2019-09-06 at 03 26 30](https://user-images.githubusercontent.com/1060248/64441032-1443b280-d09b-11e9-93c7-00c72c7ca71b.png) | ![Screen Shot 2019-09-06 at 03 26 23](https://user-images.githubusercontent.com/1060248/64409106-37983e80-d056-11e9-9816-0664374985d9.png) | ![Screen Shot 2019-09-06 at 03 26 17](https://user-images.githubusercontent.com/1060248/64409114-3b2bc580-d056-11e9-9ed6-7dc8dd841b9b.png) |
- Hide the main nav behind a menu icon on mobile.
- The sidebar and main content stack on screens narrower than 900px. The sidebar is really long. UPDATE: #319 takes care of this.
> Improve header styles and main nav responsiveness

- docs/foundation/foundation.md
Remove a "Released" tag from this higher level page
> Update "foundation" page

- CHANGELOG.md
- lerna.json
- packages/cfpb-atomic-component/package.json
- packages/cfpb-buttons/package.json
- packages/cfpb-core/package.json
- packages/cfpb-design-system/package.json
- packages/cfpb-expandables/package.json
- packages/cfpb-forms/package.json
- packages/cfpb-grid/package.json
- packages/cfpb-icons/package.json
- packages/cfpb-layout/package.json
- packages/cfpb-notifications/package.json
- packages/cfpb-pagination/package.json
- packages/cfpb-tables/package.json
- packages/cfpb-typography/package.json
Fixes https://github.com/cfpb/design-system/issues/386
> Remove unused empty file

- docs/components/atomic-components.md
- docs/components/bar-charts.md
- docs/components/base-images.md
- docs/components/buttons.md
- docs/components/code-blocks.md
- docs/components/contact-information.md
- docs/components/e-mail-signup-forms.md
- docs/components/feedback-forms.md
- docs/components/fieldsets.md
- docs/components/filterable-list-control-panels.md
- docs/components/helper-text.md
- docs/components/heroes.md
- docs/components/introductions.md
- docs/components/labels.md
- docs/components/left-hand-navigation.md
- docs/components/line-charts.md
- docs/components/lists.md
- docs/components/maps.md
- docs/components/media-queries.md
- docs/components/modals.md
- docs/components/notifications.md
- docs/components/pagination.md
- docs/components/pie-charts.md
- docs/components/quotes.md
- docs/components/radio-buttons.md
- docs/components/range-sliders.md
- docs/components/sidebars-prefooters.md
- docs/components/snippet-lists.md
- docs/components/text-inputs.md
- Add missing `last_updated` fields to component doc pages.
> Add missing `last_updated` fields

- docs/package.json
- docs/yarn.lock
Brings in the latest version of netlify-cms, 2.10.35.
> Update netlify cms dependency

- docs/admin/config.yml
- docs/components/bar-charts.md
- docs/components/blocks.md
- docs/components/buttons.md
- docs/components/checkboxes.md
- docs/components/heroes.md
- docs/components/introductions.md
- docs/components/notifications.md
- docs/components/paragraphs.md
- docs/components/text-inputs.md
- docs/foundation/iconography.md
- docs/foundation/seal.md
- Removes unused `variation_specs` entries.
Fixes https://github.com/cfpb/design-system/issues/421
> Remove unused variation_specs entries

- docs/_includes/variation-content.html
- Fixes issue where netlify was breaking on parentheses in the liquid template conditional logic, making the preview pane in the admin view blank.
1. Pull branch and run the docs locally and you should be able to edit a page and the preview won't be blank.
> Fix conditional logic

- docs/package.json
- docs/yarn.lock
Includes `--kill-others` flag to kill all processes if one exits. See https://github.com/kimmobrunfeldt/concurrently
> Replace parallelshell with concurrently to improve process handling

- docs/_includes/footer.html
- docs/_includes/header.html
- docs/_includes/search-scripts.html
- docs/_includes/search.html
- docs/_layouts/default.html
- docs/_plugins/permalinks.rb
- docs/assets/css/main.less
- docs/assets/css/search.less
- docs/assets/js/main.js
- docs/assets/js/search.js
- docs/package.json
- docs/search-results.html
- docs/webpack.config.js
- docs/yarn.lock
- Add search functionality using lunr.js
- Rename `design-system.js` to `main.js` to distinguish that it is the main entry script for the docs, not the packaged design-system components.
1. Check preview branch and see search in upper-right. Enter some text and try to break the search results.
> Add search functionality using lunr.js

- CODE_OF_CONDUCT.md
This introduces the CFPB code of conduct to the project https://github.com/cfpb/open-source-project-template/blob/master/CODE_OF_CONDUCT.md
> Introduce code of conduct

- package.json
- Adds lerna-prefixed labels to the package.json to map to new lerna labels.
> Add lerna labels to config

- packages/cfpb-atomic-component/src/components/AtomicComponent.js
- packages/cfpb-atomic-component/src/utilities/dom-traverse/index.js
- packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
- packages/cfpb-expandables/src/Expandable.js
- packages/cfpb-expandables/src/ExpandableTransition.js
- packages/cfpb-forms/src/organisms/Multiselect.js
- packages/cfpb-forms/src/organisms/MultiselectModel.js
- packages/cfpb-forms/src/organisms/MultiselectUtils.js
- packages/cfpb-forms/src/organisms/multiselect.less
- packages/cfpb-icons/src/icons-svg-inline.js
- packages/cfpb-tables/src/Table.js
- packages/cfpb-tables/src/TableSortable.js
- test/unit-test/src/cfpb-atomic-component/src/mixins/EventObserver-spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/dom-traverse-spec.js
- test/unit-test/src/cfpb-expandables/src/Expandable-spec.js
- test/unit-test/src/cfpb-tables/src/Table-spec.js
- Fix linter error and warnings
1. PR tests should pass.
> Fix linter error and warnings

- packages/cfpb-atomic-component/src/components/AtomicComponent.js
- scripts/gulp/test.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/standard-type-spec.js
- Fix minor linter issues.
1. `gulp lint` should show no errors.
> Linter fixes

- docs/assets/css/main.less
- docs/assets/js/main.js
- docs/pages/transition-patterns.md
- packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/transition.less
- Add `MaxHeightTransition` transition scripts, CSS, and demo example.
1. Check transition patterns page in the PR preview.
> Add MaxHeightTransition

- lighthouserc.js
> Fix lighthouse config

- docs/assets/css/main.less
- Constrain paragraph width and set other content to 75% width.
1. Visit the PR preview and see what you think!
> Constrain paragraph width

- .github/workflows/lighthouse.yml
- .github/workflows/pages.yml
- .github/workflows/tests.yml
- Set latest version on these actions.
> Update actions versions

- docs/pages/cards.md
- packages/cfpb-layout/src/molecules/card.less
- packages/cfpb-layout/src/organisms/card-group.less
- Adds new card patterns: topic card, topic action card, highlight card, breakout card.
- Adds new count-based (CSS Grid) and flow-based (Flexbox) card group layouts. 
- Deprecate featured cards.
1. Check the cards page on the PR preview.
> Add new card patterns

- docs/_includes/variation-content.html
- docs/assets/css/variation.less
Removed unused code and fixed some naming conventions to resolve #1269 and #1270
> Variation Cleanup

- packages/cfpb-typography/src/atoms/tagline.less
- Taglines: Fix quoting on data URI.
> Taglines: Fix quoting on data URI

- docs/pages/filterable-list-control-panels.md
Added code snippet for filterable list component into design system.
1. Visit PR preview link below
2. Visit `design-system/patterns/filterable-list-control-panels`
3. Notice "Standard filterable list" section
4. Click Show Details for code snippet
Resolves https://github.com/cfpb/design-system/issues/946
> Added code snippet for filterable list component

- packages/cfpb-layout/src/molecules/card.less
- packages/cfpb-layout/src/organisms/card-group.less
- packages/cfpb-typography/src/atoms/tagline.less
- Increase font-size of breakout card links
- Increase the spacing under card group headings
- Decrease the font size of XL taglines
1. Compare the production [cards page](https://cfpb.github.io/design-system/patterns/cards#topic-card-group) to the PR preview link below.
2. The breakout card links should be larger.
3. Card group headings should have more space underneath
4. The XL tagline text should be slightly smaller.
| <img width="657" alt="before" src="https://user-images.githubusercontent.com/1060248/144911239-bfd63f7d-c7c2-41f5-910c-908c9a5fb8db.png">  | <img width="868" alt="after" src="https://user-images.githubusercontent.com/1060248/144939470-f32eb6c1-fa92-42b8-8b1a-b4e9d0aecc64.png"> |
| <img width="574" alt="before" …
> Card and tagline changes to accommodate new homepage

- docs/pages/conducting-research-3.md
- docs/pages/design-and-development.md
- docs/pages/overview.md
- docs/pages/setting-the-foundation.md
> Add eyebrow to equity-centered design pages

- package.json
Currently building locally errors without this update
> Invoke wdio config file with .cjs locally

- .github/workflows/lighthouse.yml
- .github/workflows/pages.yml
- README.md
- Add lighthouse badge to repo.
- Update Ruby to v3 in workflows.
- Add GH token to lighthouse workflow.
1. See lighthouse passing on commit https://github.com/cfpb/design-system/pull/1522/commits/b9195aab84635f76999f8669769f92063f7c6531
> Update Ruby in workflows | set LHCI_GITHUB_TOKEN

- packages/cfpb-buttons/src/molecules/button-groups.less
Part of https://github.com/cfpb/design-system/pull/1515
> Remove combined button-groups

- packages/cfpb-design-system/src/cfpb-design-system.js
https://github.com/cfpb/design-system/pull/1523 removed the table JS, but forgot a reference. This PR removes that reference.
- Remove non-existent Table references
> Remove non-existent Table references

- docs/pages/banners.md
- packages/cfpb-atomic-component/src/utilities/atomic-helpers.js
- packages/cfpb-atomic-component/src/utilities/data-hook.js
- packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
- packages/cfpb-expandables/src/ExpandableTransition.js
- packages/cfpb-forms/src/organisms/Multiselect.js
- Fix minor linter issues and remove extraneous comments
> Fix minor linter issues and remove extraneous comments

- packages/cfpb-atomic-component/src/utilities/standard-type.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/standard-type.spec.js
This is unused.
- Remove DIRECTIONS bit values utility
> Remove DIRECTIONS bit values utility

- test/browser/docs/interstitial.js
- test/browser/docs/netlify-cms.js
- test/browser/docs/show-details.js
- test/browser/packages/cfpb-expandables.js
- test/browser/packages/cfpb-forms.js
The tests were throwing
`ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id`
Looking at https://webdriver.io/docs/async-migration/, I ran https://github.com/webdriverio/codemod, which performed the edits in this PR. I do not see the webdriver error anymore.
- Add additional async/awaits to tests.
> Tests: Add additional async/awaits

- wdio.config.cjs
- wdio.config.sauce.cjs
- Update wdio config to latest default config, which adjust some code comments, urls, timeout amounts, etc.
- Adds a dedicated sauce tunnel name.
> Update wdio config to latest

- packages/cfpb-atomic-component/src/utilities/data-hook.js
- Check if data-hook already contains a value before adding it again
> cfpb-atomic-component: Check if data-hook already contains a value before adding it again

- docs/assets/js/main.js
- packages/cfpb-atomic-component/package.json
- packages/cfpb-atomic-component/src/components/AtomicComponent.js
- packages/cfpb-atomic-component/src/index.js
- packages/cfpb-atomic-component/src/mixins/EventObserver.js
- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
- packages/cfpb-atomic-component/src/utilities/behavior/behavior.js
- packages/cfpb-atomic-component/src/utilities/standard-type.js
- packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
- packages/cfpb-expandables/src/Expandable.js
- packages/cfpb-expandables/src/ExpandableTransition.js
- packages/cfpb-expandables/src/Summary.js
- packages/cfpb-forms/src/organisms/Multiselect.js
- test/browser/docs/show-details.js
- test/unit-test/src/cfpb-atomic-component/src/components/AtomicComponent.spec.js
- test/unit-test/src/cfpb-atomic-component/src/mixins/EventObserver.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/behavior.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/data-hook.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/standard-type.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/AlphaTransition.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MoveTransition.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/type-checkers.spec.js
- Create atomic utilities index.js file for aggregating atomic utilities.
> Create atomic utilities index.js file

- docs/pages/summaries.md
- docs/pages/transition-patterns.md
- packages/cfpb-expandables/src/Summary.js
- packages/cfpb-expandables/src/summary.less
- Adjust Summary gradient to account for content area offset.
- Add another summary example.
1. PR checks should pass
> Summary: Adjustments to content overlay gradient

- .github/workflows/sauce.yml
- Update Ruby version and re-order steps in Sauce GitHub action
> Update Ruby version in Sauce GitHub action

- docs/pages/typography.md
- packages/cfpb-core/src/base.less
- cfpb-core: Add font-smoothing CSS rule to base.less file
1. In the PR preview, inspect the doc site HTML and look at the `<body>` element and see that the CSS rule `-webkit-font-smoothing: antialiased` has been added.
> cfpb-core: Add font-smoothing CSS rule to base.less file

- docs/pages/heading-hierarchy.md
- packages/cfpb-typography/src/cfpb-typography.less
- packages/cfpb-typography/src/molecules/meta-header.less
- packages/cfpb-typography/usage.md
- Update `m-meta-header` to latest spec
1. Visit https://deploy-preview-1731--cfpb-design-system.netlify.app/design-system/foundation/headings#meta-header and check out the meta header!
> Update `m-meta-header` to latest spec

- docs/pages/heading-hierarchy.md
- packages/cfpb-typography/src/molecules/meta-header.less
Refactors m-meta-header to handle different screen sizes better and to have a more uniform structure.
- Refactor `m-meta-header`
1. Check out the meta header in https://deploy-preview-1757--cfpb-design-system.netlify.app/design-system/foundation/headings#meta-header and resize to mobile
> Refactor m-meta-header

- packages/cfpb-buttons/src/atoms/buttons.less
- packages/cfpb-core/src/base.less
- packages/cfpb-core/src/utilities.less
- packages/cfpb-layout/src/cfpb-layout.less
- packages/cfpb-layout/src/molecules/heroes.less
- packages/cfpb-layout/src/organisms/card-group.less
- packages/cfpb-layout/src/organisms/email-signup.less
- packages/cfpb-layout/src/organisms/featured-content-module.less
- packages/cfpb-layout/src/organisms/wells.less
- packages/cfpb-notifications/src/molecules/notification.less
- packages/cfpb-notifications/src/organisms/banner.less
- packages/cfpb-pagination/src/molecules/pagination.less
- packages/cfpb-tables/src/cfpb-tables.less
- packages/cfpb-typography/src/molecules/list.less
- packages/cfpb-typography/src/molecules/meta-header.less
- packages/cfpb-typography/src/molecules/pull-quote.less
Follow up to https://github.com/cfpb/design-system/pull/1785/ to remove duplicate margin setting. 
Also, add human-readable code comments for responsive style helpers.
- Remove duplicate margin.
- Add human-readable code comments for responsive style helpers.
1. PR checks should pass. Lead paragraph on landing page of PR preview should be unchanged.
> Remove redundant margin | add responsive style code comments

- docs/pages/cards.md
- packages/cfpb-layout/src/molecules/card.less
Removes deprecated and unused featured and highlight card patterns.
- Removed highlight and featured cards
1. View https://deploy-preview-1850--cfpb-design-system.netlify.app/design-system/patterns/cards and see that the featured and highlight cards are gone.
> Removed highlight and featured cards

- packages/cfpb-layout/src/molecules/card.less
Follow up to https://github.com/cfpb/design-system/pull/1850
- Cards: Cleanup redundant CSS
1. Cards should be unchanged
> Cards: Cleanup redundant CSS

- packages/cfpb-layout/src/molecules/heroes.less
When we work on the hero it's likely we'll work on it at particular screensizes, versus particular elements. 
- Organizes the hero less by screen size.
1. Compare https://deploy-preview-1866--cfpb-design-system.netlify.app/design-system/patterns/heroes to https://cfpb.github.io/design-system/patterns/heroes and they should be unchanged.
> Format hero CSS by screensize

- docs/pages/wells.md
- packages/cfpb-layout/src/organisms/wells.less
- Remove deprecated inkwell component.
1. Inkwell should be gone from https://deploy-preview-1869--cfpb-design-system.netlify.app/design-system/patterns/wells
> Remove inkwell

- docs/_includes/footer.html
- docs/_includes/variation-content.html
- docs/pages/design-and-development.md
- Move latest updates to the bottom of the template
1. PR preview should have latest updates in the content area of the page.
> Move latest updates to the bottom of the template

- .github/workflows/lighthouse.yml
- .github/workflows/pages.yml
- .github/workflows/publish.yml
- .github/workflows/sauce.yml
- .github/workflows/tests-unit.yml
- Update node to v20
1. PR checks passed.
> Update node to v20

- .github/workflows/lighthouse.yml
- .github/workflows/sauce.yml
- netlify.toml
- Align all ruby versions on 3.2.3
> Align all ruby versions on 3.2.3

- docs/pages/e-mail-signup-forms.md
- docs/pages/heading-hierarchy.md
- packages/cfpb-typography/usage.md
These were removed in cfgov in https://github.com/cfpb/consumerfinance.gov/pull/8362
- Remove `datetime` elements
> Remove `datetime` elements

- docs/pages/variables.md
- packages/cfpb-layout/src/cfpb-layout.less
- packages/cfpb-layout/usage.md
- Remove `@content__sidebar` variables
> Remove `@content__sidebar` variables

- docs/pages/links.md
- docs/pages/variables.md
- packages/cfpb-typography/src/cfpb-typography.less
- packages/cfpb-typography/usage.md
Fixes https://github.com/cfpb/design-system/issues/1974
- Remove unused `@jump-link`
- Update `icon-link` to `a-link`
> Update `icon-link` | Remove unused `@jump-link`

- packages/cfpb-atomic-component/README.md
- packages/cfpb-buttons/README.md
- packages/cfpb-core/README.md
- packages/cfpb-design-system/README.md
- packages/cfpb-expandables/README.md
- packages/cfpb-forms/README.md
- packages/cfpb-grid/README.md
- packages/cfpb-icons/README.md
- packages/cfpb-layout/README.md
- packages/cfpb-notifications/README.md
- packages/cfpb-pagination/README.md
- packages/cfpb-tables/README.md
- packages/cfpb-typography/README.md
These travis-ci badges are outdated and broken and can be removed.
- Remove travis-ci badges
> Remove travis-ci badges

- docs/pages/text-inputs.md
Fix text input notification colors broken in #1973.
> Fix text input notification colors

- docs/assets/css/main.less
I can't find any references to this variable.
- Remove `@cf-icon-path`
> Remove `@cf-icon-path`

- packages/cfpb-design-system/src/abstracts/index.js
- packages/cfpb-design-system/src/abstracts/vars-breakpoints.js
- packages/cfpb-design-system/src/utilities/breakpoint-state.js
> Remove default export

- packages/cfpb-design-system/src/index.scss
This allows importing all styles via one entrypoint.
- Create root package index.scss
> Create root package index.scss

- packages/cfpb-design-system/src/components/cfpb-typography/meta-header.scss
- Fix malformed line-height
1. Check headings page on PR preview.
Before:
After:
> Fix malformed line-height

- docs/assets/css/main.scss
- packages/cfpb-design-system/src/index.scss
> Linter autofixes

- packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
We need to increase the gap between tags for touch target reasons.
- Update gap in tags
1. Check gap on https://deploy-preview-2046--cfpb-design-system.netlify.app/design-system/components/tags#topic-tag-stacked
> Update gap in tags

- package.json
Test out adjustments to release-it config
> Adjust release-it config

- package.json
Further adjust release-it config
Registry added because of yarn https://github.com/release-it/release-it/blob/eeda65b820c2c1c8b77d21280b717098db1e336c/docs/npm.md#yarn
> Further adjust release-it config

- packages/cfpb-design-system/src/abstracts/custom-props.scss
- packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
Minor adjustments to code comments.
> Adjust code comments

- .github/actions/shared-action-setup/action.yml
- .github/workflows/cypress.yml
- .github/workflows/lighthouse.yml
- .github/workflows/pages.yml
- .github/workflows/tests-unit.yml
- Create shared action for the GH action workflows so that they share the setup steps.
> Create shared setup action for the GH action workflows

- .github/workflows/pages.yml
- Fix indenting in `workflows/pages.yml`
> workflows/pages.yml - Fix indenting

- packages/cfpb-design-system/README.md
- Point to the right npm repo in the DS
> Point to the right npm repo in the DS

- cliff.toml
- packages/cfpb-design-system/src/utilities/atomic-helpers.spec.js
- packages/cfpb-design-system/src/utilities/behavior/behavior.spec.js
> Add behavior JS unit tests

- packages/cfpb-design-system/README.md
I updated the link for this, but the badge image needs updating too!
- Fix badge URL
> Fix npm badge image URL

- docs/pages/grid.md
- docs/pages/heading-hierarchy.md
Minor cleanup on outdated mixin references
> Update mixin references

- scripts/release.sh
- Update release script for more reporting and checking.
1. Unset `GITHUB_TOKEN` and run `./scripts/release.sh` and it should now prompt you if `GITHUB_TOKEN` is not set.
> Update release script for more reporting and checking

- docs/_includes/search.html
- docs/assets/css/header.scss
- docs/assets/css/search.scss
- test/cypress/e2e/docs/search.cy.js
Fixes https://github.com/cfpb/design-system/issues/2215
- Update doc search input to use standard input
1. Try out the global search in the PR preview.
-  There's a bug where the width of the input changes when text is entered, see https://github.com/cfpb/design-system/issues/2223
> Update doc search input to use standard input

- docs/_includes/search.html
Follow up to this missed in https://github.com/cfpb/design-system/pull/2224
- Remove doc site search input placeholder
> Remove doc site search input placeholder

- .github/actions/shared-action-setup/action.yml
- Gemfile
- README.md
- netlify.toml
- Update Ruby and Node
- Update Ruby dependencies
1. Follow updated installing Ruby instructions https://github.com/cfpb/design-system/pull/2233/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5. `yarn start` should be good.
> Update Ruby and Node

- .editorconfig
- Migrate editorconfig `less` reference to `scss`
> Migrate editorconfig `less` reference to `scss`

- docs/_includes/examples/alerts.html
- docs/_includes/examples/search-input.html
- docs/_includes/search.html
- Fix aria labelling on search input.
- Update IDs to use dashes in alerts.
> Fix aria labelling
