cfpb/design-system

- docs/admin/config.yml
- docs/admin/src/netlify-cms.js
- docs/admin/src/widgets/navigation/secondaryPreview.js
- docs/admin/src/widgets/navigation/sectionPreview.js
- docs/admin/src/widgets/navigation/tertiaryPreview.js
- docs/admin/src/widgets/noPreview.js
Added a bare bones preview of the nav hierarchy by cheaply adding non-breaking spaces to indent the items. I also created a string widget without a preview for general use.
> Clean up CMS navigation link previews

- docs/_data/navigation.yml
- docs/_includes/sidebar.html
Only output a link element if there is a slug (aka URL) present in the data (added via CMS). If there is no `slug` value then we just output the text. For example, on components pages the second level in the nav is just headings and those are not pages that go anywhere, so this PR fixes them to look like it:
For pages that we want to make links, just enter a slug value into the CMS and they will appear as links.
-
-
-
1.
-
-
> Make secondary nav element a link if there is a slug, just text if not

- docs/_includes/sidebar.html
- fixes secondary nav link with correct slug, before it was outputting the section slug instead of the secondary nav item slug
- fixes tertiary nav link URLs so that it outputs the slug instead of automatically including the section slug in the url
-
-
-
1.
-
-
> Fix sidebar template to output slugs as correct URLs

- docs/Gemfile
- docs/_includes/component.html
- docs/_plugins/render_includes.rb
- docs/components/buttons.md
- docs/components/iconography.md
- docs/components/text-inputs.md
- docs/package.json
- docs/pages/beam-pattern.md
- docs/pages/logo.md
Jekyll doesn't render our `{% include %}` statements because they're stored as strings in our pages' front matter. Using a Jekyll hook we can swap out our include statements with inline SVGs.
See hubcap issues #240 and #221.
Before: https://cfpb.github.io/design-system/foundation/iconography#variations (scroll down to icon table)
After: https://deploy-preview-166--cfpb-design-system.netlify.com/design-system/foundation/iconography#variations
> Add Jekyll post render hook to inline icon SVGs

- docs/_layouts/component.html
- docs/_layouts/generic-page.html
- docs/_layouts/homepage.html
- docs/assets/css/netlify.less
Moves the "add" button into its own fixed location below the edit button.
> Separate CMS button shortcuts

- docs/_layouts/variation.html
Instead of generating an edit URL by slugifying the page's title, get
the page's markdown filename by removing directories and the file
extension from the page's path.
See hubcap/issues/286 for context.
1. Go to https://cfpb.github.io/design-system/components/headings and click the edit button.
1. Note how you 404 because it took you to `/admin/#/collections/components/entries/headings` and the markdown filename is `heading-hierarchy.md` not `headings.md`.
1. Go to https://deploy-preview-243--cfpb-design-system.netlify.com/design-system/components/headings and click the edit button.
1. It should correctly load because it took you to `/admin/#/collections/components/entries/heading-hierarchy`.
> Fix edit button URLs

- docs/admin/config.yml
Changes the CMS label for the Title field to "Page title."
> Change label to Page title for CMS

- docs/_includes/variation-content.html
- docs/assets/css/code.less
- docs/assets/css/header.less
- docs/assets/css/tabs.less
- docs/assets/css/variation.less
- docs/assets/js/main.js
Applies CFPB styles to the GovUK tabs we're using. We may want to
formally fork their tabs and redesign them for our design system. For
now we're just tweaking their CSS to make it more CFPBy.
See hubcap/issues/291 for context.
Before:
After:
> Re-style tabs, make them responsive

- package.json
I have run `yarn start` from the project root multiple times and I forgot every time why it doesn't work, now I have computer to remind me 
-
-
-
1.
-
-
> add message for console when developer runs yarn start from wrong dir

- docs/home.md
Fixes links for issues and pull requests
- changes links from design-manual to design-system
-
> Fix links from design-manual to design-system

- docs/assets/css/secondary-nav.less
Replaces https://github.com/cfpb/design-system/pull/368
- Change margin and padding on sidebar CSS so that multi-line items are indented correctly.
1. Pull branch, run local docs, see that sidebar is indented versus live version.
Before:
After:
> Fix sidebar indenting CSS

- docs/components/e-mail-signup-forms.md
- docs/components/info-unit-groups-image-text.md
- docs/components/links.md
- docs/components/megamenu.md
- docs/components/quotes.md
Templates that have an empty restrictions array do not show their usage section. 
Fixes https://github.com/cfpb/design-system/issues/357
- Remove empty restrictions from component templates.
> Remove empty restrictions (bug)

- packages/cfpb-forms/src/atoms/select.less
- packages/cfpb-icons/src/icons-svg-inline.js
Somewhere along the way the icon utility got misnamed (maybe in https://github.com/cfpb/design-system/commit/c5ed1312cfa258c407edf429feba33f869c5ff56#diff-6f832afbd954a937aea89c317ed308b0). This fixes it.
- Fixes inline icon utility path names.
- Includes cfpb-icons in the select.less by reference, so utility is always available when that file is imported.
1. Pull branch and `cd doc && yarn && yarn start` and visit http://localhost:4000/design-system/components/dropdowns-and-multi-selects and see that the drop-down has an icon.
> Fix misnamed icon utility

- docs/components/banners.md
- packages/cfpb-notifications/src/cfpb-notifications.less
- packages/cfpb-notifications/src/organisms/banner.less
- Add "banners" organism component page to design system.
1. Pull branch and `cd docs on && yarn && yarn start`
2. Visit http://localhost:4000/design-system/components/banners and see there is a basic default banner shown! Ta-da!
> Add "banners" organism component page to design system

- docs/package.json
- docs/webpack.config.js
- docs/yarn.lock
- package.json
- Change `private` attribute in `package.json` from string to valid boolean.
- Add required `version` attribute to `package.json`.
- Remove `main` attributein `package.json` that pointed to JS file that doesn't exist.
- Move `devDependencies` next to `dependencies` in `package.json`.
- Change `homepage` attribute in `package.json` to the github pages URL, not the repo.
- Remove unused `copy-webpack-plugin`.
> Fix package.json issues | Remove unused copy-webpack-plugin

- packages/cfpb-core/src/base.less
Because IE does not support the `initial` value, and `inherit` works just fine.
These were added in https://github.com/cfpb/capital-framework/pull/784 in order to prevent H5s and H6s styled as larger headings from being uppercased and letter-spaced.
- `letter-spacing` and `text-transform` resets in `heading-` mixins now use `inherit` instead of `initial`
I had difficulty getting the Design System site running locally, but I tested the changes by manually editing the `node_modules/@cfpb/cfpb-core/src/base.less` file in cfgov-refresh.
> cf-core: Use inherit instead of initial on heading mixins

- docs/assets/js/main.js
Was checking for `undefined` on DOM query that returned no results, but the result in that case would actually be `null`.
- Check that not found element is `null` not `undefined`.
> Check that not found element is null not undefined

- docs/assets/css/secondary-nav.less
Fixes sidebar that was hidden from the change in https://github.com/cfpb/design-system/pull/406
- Ensure collapsed expandable is visible when overflow is overridden
1. Sidebar in e.g. https://cfpb.github.io/design-system/components/expandables should be visible.
> Ensure collapsed expandable is visible when overflow is overridden

- docs/_includes/variation-content.html
- Checks if the variations array is empty before showing it.
1. Check https://cfpb.github.io/design-system/components/atomic-components and see that there's an empty variation section. Compare to the same page in the preview branch in this PR. 
2. Check that the buttons page still has the variations.
> Hide empty variations

- docs/assets/js/main.js
See https://github.com/cfpb/design-system/pull/438#issuecomment-612189098.
1. Compare the [live site](https://cfpb.github.io/design-system/components/cards) to this PR's [preview site](https://deploy-preview-443--cfpb-design-system.netlify.com/design-system/components/cards)
1. When you hover over "Bank accounts" there should be no link icon.
- The library used is https://www.bryanbraun.com/anchorjs/.
> Ensure live code examples have no anchor links

- docs/assets/css/header.less
- docs/assets/css/main-content.less
- docs/assets/css/secondary-nav.less
Limits line lengths to our standard `41.875rem` and sets the main and side nav links to be pacific except on hover when they're navy.
- Color of side and main nav links.
- `max-width: inherit;` that was overriding cf-layout's [max-width](https://github.com/cfpb/capital-framework/blob/0b15295c00ba1972676b6f4c86f3b40dcf45289d/packages/cf-layout/src/cf-layout.less#L252).
1. Compare a [production page](https://cfpb.github.io/design-system/components/checkboxes) to a [PR preview page](https://deploy-preview-444--cfpb-design-system.netlify.com/design-system/components/checkboxes).
- By default, Netlify CMS wraps images in `p` tags, meaning their max width is also constrained. When we start experimenting with new image layouts we'll need to ensure they don't get wrapped in `p`s.
- The main nav …
> Improve navigation link colors and add a max line length

- docs/assets/css/color-swatches.less
- docs/assets/css/main.less
Brings over the [color swatch CSS](https://github.com/cfpb/design-manual/blob/9e8d7a6718a2d68226ebd2e570d6c5e45afd2648/src/static/css/content.less#L218) from the design manual so that the color page no longer looks bonkers.
- Color swatch stylesheet
1. Compare [production](https://cfpb.github.io/design-system/foundation/color) to the [PR preview](https://deploy-preview-447--cfpb-design-system.netlify.app/design-system/foundation/color).
> Copy over color swatch styles from design manual

- docs/Gemfile
- docs/_config.yml
- docs/_includes/footer.html
- docs/admin/config.yml
- Adds `jekyll-last-modified-at` for providing a last modified date stamp in the footer.
1. Check the PR preview link below and see that last modified date in the footer of pages.
> Add last modified date

- docs/admin/config.yml
Sets [`minimal: true`](https://www.netlifycms.org/docs/widgets/#markdown) on every markdown field to make them less huge.
1. Edit a page using the PR preview link below and the markdown fields should be smaller when empty.
| Before | After |
| <img width="640" alt="Screen Shot 2020-04-23 at 11 17 34 PM" src="https://user-images.githubusercontent.com/1060248/80171666-f343b980-85b8-11ea-97f5-83591c544b28.png">   | <img width="873" alt="Screen Shot 2020-04-23 at 11 15 22 PM" src="https://user-images.githubusercontent.com/1060248/80171662-f179f600-85b8-11ea-95be-fd985b0fa429.png">  |
> Shrink the markdown widgets

- docs/assets/js/main.js
- scripts/gulp/lint.js
- Add documentation site JS to the gulp linter script.
1. `gulp lint` should include doc/assets/js/main.js
> Add doc JS to linter

- .github/workflows/pages.yml
- .travis.yml
- scripts/update-gh-pages.sh
Travis has proven unreliable so we should migrate our CI to GitHub Actions. This PR migrates the gh-pages deployment step. In a future PR we can migrate our PR tests.
- `deploy` GitHub Actions job.
- Shell script that builds the website and pushes it to gh-pages.
- Travis CI deployment step.
1. Hmmmmmm. Merge this PR and see if the action completes?
- Migrate PR tests to GitHub Actions.
- [Configure caching](https://github.com/actions/cache/blob/master/examples.md#node---yarn) to greatly speed up the website build time.
> Replace Travis CI deployment step with GitHub Actions

- docs/_includes/generic-content.html
- docs/_layouts/homepage.html
- docs/admin/config.yml
- docs/admin/src/netlify-cms.js
- docs/admin/src/widgets/genericPreviewTemplate.js
- docs/home.md
Adds netlify [file collection](https://www.netlifycms.org/docs/collection-types/#file-collections)  called 'Generic pages' that is used for one-off pages with unique layouts. Currently, the homepage is the only item in this collection. A jinja template and netlify preview template was created to unintelligently render whatever HTML and markdown is added to a generic page's "body" field.
- Netlify CMS file collection w/ homepage file.
- Template for rendering and previewing "generic content", i.e. a freeform text field containing HTML and/or markdown.
- Edit button on homepage.
1. Compare the [production homepage](https://cfpb.github.io/design-system/) to this [PR preview homepage](https://deploy-preview-456--cfpb-design-system.netlify.app/design-system). They should be the same.
1. Click …
> Make homepage editable via the CMS

- docs/admin/config.yml
Netlify used to require access to all public and private repos in order
to use their CMS. They have since added a config option to only require
access to users' public repos.
Fixes #420.
1. Try editing a page at the PR preview link below and confirm that when authenticating with Netlify only access to public repos is requested.
> Reduce scope of Netlify CMS permissions

- docs/assets/css/search.less
- docs/search-results.html
- Sets the max line width by enclosing the search results in `content_main` class.
1. See preview and perform a search and see that results aren't as wide as before.
Before:
After:
> Search: Set max line width on results

- docs/Gemfile
- docs/_config.yml
We're not using this plugin right now, so removing it until such time as we want or need to support redirects this way.
> Remove unused redirects plugin

- README.md
- docs/admin/config.yml
- docs/package.json
- docs/yarn.lock
Add support for and document running against a local GitHub proxy server instead of against the live branch on GitHub.com.
This is a beta feature of Netlify CMS:
https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
I've pushed this commit to master on my fork, and you can see that [my fork's GH pages](https://chosak.github.io/design-system/) edit buttons still try to authenticate to GitHub.com; but if you [run this branch locally](http://localhost:4000/design-system/), it will use the local proxy server, but only if is running. If you're not running a local proxy server, local development still falls back to the GitHub backend.
Per the netlify-cms code, the CMS only looks for the local proxy [if running on …
> Add support for optional local backend

- scripts/update-gh-pages.sh
Currently we run the gh-pages GitHub Action even if there are no changes in the documentation website.
There's a line that tries to exit early if there are no changes to commit, but it doesn't work properly. Because we use `set -e` at the top of the script, when 'git commit' returns 1 (if there are no changes to commit), it causes the script to fail with an error.
For example, that happened on this Actions run:
https://github.com/chosak/design-system/runs/637557200
Note the message right before failure with "nothing to commit, working tree clean". This also returns a non-zero status code, which causes the script to fail.
This commit instead first checks to see if there are any changes to commit, and gracefully exits if not.
An example run where there was a graceful exit: …
> Fix GH Actions script when no changes exist

- docs/_includes/search-scripts.html
- docs/assets/js/main.js
- docs/assets/js/search.js
- Fix missing variations field search by including new variations_group parent.
- Add `research` and `related_items` fields to search.
- Highlight search term in results with `<mark>` element.
1. Perform a search on PR preview.
> Fix variations search | add search fields | highlight search term

- .gitignore
- docs/Gemfile
- docs/_config.yml
- docs/_includes/sidebar.html
- docs/_layouts/default.html
- docs/_layouts/homepage.html
- docs/_layouts/variation.html
- docs/package.json
This commit updates Jekyll to version 4. Closes #465.
See these pages for documentation on the upgrade:
https://jekyllrb.com/news/2019/08/20/jekyll-4-0-0-released/
https://jekyllrb.com/docs/upgrading/3-to-4/
Minor changes include:
- Tried to use the built-in `relative_url` filter instead of having numerous references to site.baseurl.
- Added --profile to `yarn watch` to make it easier to keep track of build times.
To test, run `bundle update`, then `yarn`, and `yarn start`.
You might seem some errors like "Empty `slug` generated for ''" -- these are because we have some empty variation names and, as of Jekyll 4, the use of `| slugify` on these generates a warning. These should be fixed but that is independent of this upgrade -- note for example the empty variation names on …
> Upgrade to Jekyll 4

- docs/foundation/accessibility.md
Fixes broken bullet links on https://cfpb.github.io/design-system/foundation/accessibility.
> Fix broken anchor links on accessibility page

- docs/_includes/footer.html
- docs/assets/css/footer.less
- All the CSS rules in `footer.less` that aren't used anywhere. 
- Links pages' "Last edited" timestamp to their GitHub history pages.
1. Check out the PR preview link below.
> Add link to pages' GitHub history in footer

- docs/_includes/search-scripts.html
- docs/assets/css/search.less
- docs/assets/js/search.js
- Exclude search page itself from search results.
- Omit preview text if there aren't any fields to pull from (e.g. search for "homepage").
- Provide a result count and term at the top of search results.
- Provide search term in no results display.
- Don't float the search input box on mobile.
1. Check preview and search for "homepage", "search", "block__flush", etc. and resize to mobile.
> Search refinements

- docs/_includes/variation-content.html
- docs/assets/css/variation.less
- Convert restrictions do/do not section to use an icon instead of a bar.
1. Check buttons page on the PR preview, or any other page that has a restrictions section.
Before:
After:
- The restrictions section should just be deleted, really
> Convert restrictions do/do not to use icon

- docs/_config.yml
Override server settings to ensure our "page last edited" timestamps show DC time.
- Jekyll timezone no longer defaults to the local machine's timezone.
1. The PR preview for the homepage should show [1:51 PM](https://deploy-preview-490--cfpb-design-system.netlify.app/design-system/) in the footer and not [5:51 PM](https://cfpb.github.io/design-system/).
> Set sitewide timezone via Jekyll config

- docs/_includes/variation-content.html
- "Show details" instead of "show source"
1. View a [component page](https://deploy-preview-491--cfpb-design-system.netlify.app/design-system/components/checkboxes) at the PR preview link below and enjoy the new text.
> Update text of code toggling button

- docs/admin/src/widgets/variationPreviewTemplate.js
- docs/package.json
- docs/webpack.config.js
- docs/yarn.lock
- test/browser/docs/code-snippets.js
- test/browser/docs/netlify-cms.js
- test/browser/packages/cfpb-expandables.js
A little hacky but it works and I'm unsure of a better way. I added a browser test to catch future regressions.
- The variation template strips out any icon include statements before rendering.
1. Cloud browser tests should pass below.
1. `yarn test:browser` should pass locally.
1. Editing the buttons pages on the [PR preview](https://deploy-preview-493--cfpb-design-system.netlify.app/design-system/admin/#/collections/components/entries/buttons) should correctly show the preview pane while on [production](https://cfpb.github.io/design-system/admin/#/collections/components/entries/buttons) it throws an error and is blank.
> Inject SVG icons before rendering preview in Netlify CMS

- docs/_includes/variation-content.html
- Adjust heading size and padding on restrictions to address layout issues.
1. Check PR preview page with restrictions, such as the buttons page.
> Fix restrictions layout

- docs/_includes/variation-content.html
- Check for empty variation fields (which are optional)
1. Edit a page in the preview PR and see that if you have an empty variation name or variation description those empty sections don't show up in the markup.
> Check for empty variation fields

- docs/_includes/variation-content.html
- docs/admin/src/widgets/variationPreviewTemplate.js
- docs/assets/js/main.js
- docs/assets/js/tabs.js
- docs/assets/js/toggle-details.js
- docs/package.json
- docs/yarn.lock
- test/browser/docs/code-snippets.js
- test/browser/docs/netlify-cms.js
- test/browser/webdriver-sauce.conf.js
Fixes the "show details" link within Netlify CMS's live preview pane. The Gov UK tabs we use modifies the URL's hash which doesn't play well with Netlify CMS so a simpler version of the tab switching is provided for the CMS.
- Simplified version of the Gov UK tab switching code for the CMS to use.
- Browser test that clicks some "show details" tabs in the CMS.
- Slugify liquid filter for the preview pane (before this PR, the `slugify` filter erroneously wasn't being recognized)
- Moves the "show details" and tabs code into their own files so they can be imported as needed.
1. Cloud browser tests should pass below.
1. `yarn test:browser` should pass locally
1. Editing a page with variation details (like buttons) via this PR's preview link should show functioning tabs while …
> Fix "show details" functionality in CMS

- docs/_includes/variation-content.html
- docs/components/heading-hierarchy.md
- docs/components/helper-text.md
- docs/components/notifications.md
- docs/components/text-inputs.md
We were erroneously checking for only component restrictions and use cases when rendering component pages, resulting in editors having to put dummy content in the use cases field to get anything to appear. We should check for all four sections: use cases, content guidelines, behavior and restrictions.
Fixes: GHE/CFPB/el-camino/issues/238
- Check for the existence of `page.content_guidelines` and `page.behavior` along with restrictions and use cases.
1. The [PR preview](https://deploy-preview-548--cfpb-design-system.netlify.app/design-system/components/headings#use-cases) headings page should not have a Use Cases section while  [production](https://cfpb.github.io/design-system/components/headings#use-cases) has a placeholder period in that section.
> Fix component template rendering logic

- docs/_includes/search-scripts.html
Search was breaking when content contained single quotes. This changes the filter used to escape single quotes.
- Change `xml_escape` to `escape` filter.
1. On this PR's preview branch search for "image" and see that there are search results.
> Search: Convert xml_escape filters to escape to handle single quotes

- docs/_includes/search-scripts.html
Stripping newlines like this means that text in headings gets erroneously combined with subsequent lines. For example, try this search:
https://cfpb.github.io/design-system/search/?searchQuery=coherent
This returns no results, incorrectly. Now try this one:
https://cfpb.github.io/design-system/search/?searchQuery=reaching.coherent
This search shouldn't work.
This change removes the use of `strip_newlines`.
Fixes el-camino#264.
> Don't strip newlines from search index

- docs/_includes/variation-content.html
- docs/assets/css/variation.less
Thanks to @Scotchester for the suggestion.
To test, visit a page like https://cfpb.github.io/design-system/components/buttons in a narrow browser, and observe how the buttons wrap.
|Current|With this change|
|-|-|
|![image](https://user-images.githubusercontent.com/654645/86249940-ed9cbe00-bb7d-11ea-92c2-09a6368cdc01.png)|![image](https://user-images.githubusercontent.com/654645/86249963-f5f4f900-bb7d-11ea-9ba0-ee06ef8bf0a7.png)|
> Add spacing when long lists of jump links wrap

- docs/_includes/redirect-banner.html
- docs/_layouts/default.html
- docs/assets/js/main.js
When visitors are redirected from the soon-to-be-deprecated [Capital Framework](https://cfpb.github.io/capital-framework/) and [Design Manual](https://cfpb.github.io/design-manual/) websites, the landing URLs will have certain query string parameters:
?utm_medium=redirect&utm_source=capitalframework
?utm_medium=redirect&utm_source=designmanual
When this traffic comes in, we want to show a banner to users to let them know they've been redirected.
This change adds that banner using JavaScript.
When visiting http://localhost:4000/design-system/?utm_source=capitalframework&utm_medium=redirect:
When visiting http://localhost:4000/design-system/?utm_source=designmanual&utm_medium=redirect:
I'd very much welcome feedback on the JS implementation of this. I wasn't sure if there was some better …
> Add banner when redirected from CF/DM

- docs/assets/js/main.js
- docs/assets/js/redirect-banner.js
- docs/assets/js/search.js
- docs/assets/js/toggle-details.js
- test/browser/webdriver-sauce.conf.js
Fixed some issues flagged by the linter.
- Moves redirection banner to its own script file.
- Breaks redirection script into functions to reduce complexity warnings.
- Fixes missing jsdoc argument in search script.
- Fixes undefined variable warning in search script.
- Minor spacing and quotation autofixes from linter.
1. Redirection and search should work as before.
> Linter fixes

- docs/pages/accessibility.md
- docs/pages/general-principles.md
- `section` and `secondary_section` are set to `null` on accessibility and general principles pages.
> Accessibility and General Principles pages: Remove sections

- .github/workflows/docs-a11y.yml
- .gitignore
This PR adds a new GitHub Action for running [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) against the Design System documentation site. The full site is tested with Lighthouse every night at midnight UTC, using an emulated desktop browser. Results are both uploaded to Google's temporary public storage as well as attached to the Github Actions run as an artifact.
See an example run on my fork [here](https://github.com/chosak/design-system/runs/870959613?check_suite_focus=true). From testing it takes between 15 and 20 minutes to run against the full site.
> Add GitHub Action for running Lighthouse CI

- docs/_includes/footer.html
The recent IA change moved every page of the website into the `/docs/pages/`
directory with the exception of one-off special pages like the homepage
and the how-to page. Those live in `/docs/special-pages/` and have a
`collection_name` property created by netlify-cms indicating their specialness.
- URL to GitHub history pages in footer
1. Go to any page of the PR preview link below and click on the timestamp in the footer. They should all take you to a GitHub history page and not 404.
> Fix footer timestamp links to GitHub histories

- docs/_layouts/variation.html
- docs/assets/css/netlify.less
- docs/assets/js/main.js
- docs/assets/js/toggle-details.js
- test/browser/docs/show-details.js
- test/browser/webdriver-sauce.conf.js
- Adds a toggle details button that toggles the show/hide button for details.
- Makes the edit page button (and the toggle all button) always show text.
1. Visit the PR preview branch and find a page that has details, such as buttons, and click the toggle details button in the lower-right.
- Is the state of the toggled details retained across pages? If so we need to save a cookie or similar.
- If some details are showing and some others aren't, how should the toggle button work?
> Add toggle all details button

- docs/_includes/variation-content.html
This will hopefully prevent [empty related items sections](https://cfpb.github.io/design-system/foundation/iconography#related-items) from rendering.
- Related items logic
1. PR preview link below should not have an empty related items section on the iconography page.
> Properly check if related items section is empty

- docs/assets/css/color-swatches.less
We have some unique colors that are used in our data visualizations
but haven't made their way into our official brand-colors.less stylesheet.
To prevent empty color swatches from appearing in our data viz section of
the website, I have manually created their CSS classes.
- Data viz color CSS classes.
1. [These tables](https://cfpb.github.io/design-system/foundation/color#data-visualization-palettes) have empty color sections while the [same tables of the PR preview website](https://deploy-preview-930--cfpb-design-system.netlify.app/design-system/foundation/color#data-visualization-palettes) do not.
| <img width="904" alt="Screen Shot 2020-07-17 at 1 19 49 PM" src="https://user-images.githubusercontent.com/1060248/87813672-5ea3cd00-c830-11ea-9ee1-076be …
> Add data viz color swatch classes

- docs/_layouts/homepage.html
- docs/_layouts/variation.html
- docs/assets/js/main.js
- docs/assets/js/toggle-details.js
- Add local storage for remembering the toggle state across pages on the DS.
- Change "Edit this page" to "Edit page"
1. View the PR preview branch and click the Show all details button on a component page and then visit another component page and see that the toggle is in the same state. Close the session and open the PR preview branch again and see that the toggle button is in the same state as when you last visited.
> Add local storage for remembering the toggle state

- docs/pages/tables.md
- Add missing closing div for filter.
- Remove unused `o-expandable__filters` class.
- Remove erroneously added `data-bound=true` attribute that should be added by the JS.
1. Visit tables page in PR preview and go to the filterable table example and the "filter" should be able to be opened.
> Fix filterable table example

- docs/_includes/footer.html
- docs/_layouts/default.html
- Update site footer text.
- Remove footer on homepage.
1. Visit branch preview PR and see that there is no footer on the homepage and other pages have updated footer text.
> Update site footer and remove from homepage

- docs/_includes/variation-content.html
- docs/assets/css/tabs.less
- docs/assets/css/toggle-code-button.less
- docs/assets/css/variation.less
Horizontal rules separating variations was tied to variations' 'toggle details'
element. Thus, variations without any details to toggle lacked the line.
There was also no padding at the end of variation groups when the final
variation lacked details.
See https://[GHE]/CFPB/el-camino/issues/274
- Variation and toggle code Less.
1. In the PR preview below, there should be lines between the [logo lockups](https://cfpb.github.io/design-system/foundation/logo#lockups-1).
1. In the PR preview below, there should be padding at the bottom of the [email signup variations section](https://cfpb.github.io/design-system/patterns/e-mail-signup-forms#when-other-options-are-better).
| <img width="905" alt="Screen Shot 2020-07-15 at 1 04 12 PM" …
> Fix variation horizontal rules and bottom padding

- docs/admin/config.yml
- docs/admin/src/netlify-cms.js
- docs/admin/src/widgets/StringWithInstructions.js
Puts a sentence under pages' title field in the CMS directing users to our how-to page. It's done by creating a new widget that's identical to our string widget with the addition of a hyperlink.
This approach adds some redundant code but adding/editing widgets is the sustainable method of modifying the CMS's left-hand editing pane. The alternative would be forking netlify-cms and tweaking its source code which is a maintenance headache.
- `StringWithInstructions` widget
1. Cloud browser tests should pass below.
1. Everything should function as normal.
1. Try editing a page via the PR preview link below and you should see the new sentence under the title field.
I wanted to put the help text at the very top of the page, above all the fields BUT netlify doesn't let you touch the area above a …
> Add link to CMS instructions page for new users

- docs/assets/js/sidebar.js
iOS triggers a resize event when scrolling that was causing the navigation menu to close unexpectedly. This PR first checks if the window size has actually changed before closing the menu.
- Check that window size has changed before closing or opening the sidebar navigation menu.
1. Pull branch and run locally. 
2. Open the iOS simulator (Applications > Xcode > [right-click Show Package Contents] > Contents > Developer > Applications > Simulator.app)
3. Open the localhost:4000/design-system in the Simulator.
4. Open the navigation menu.
5. Scroll down the page. The menu should not close on its own.
> Fix iOS navigation bug

- _config.yml
- lighthouserc.js
- scripts/build-netlify-pr-preview.sh
- scripts/update-gh-pages.sh
Currently we build the docs under `docs/_site`. Instead let's build them under `docs/_site/design-system`, which will simplify a couple of downstream consumers.
Hopefully the Netlify preview site builds properly here.
> Build docs into design-system subdirectory

- docs/pages/notifications.md
The [notifications page](https://cfpb.github.io/design-system/components/notifications) was missing labels on some of the examples. See example Lighthouse report [here](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1595876527951-92755.report.html).
I've added simple labels, for example `<label class="a-label a-label__heading" for="form-input-warning">Input label</label>`.
> A11y: Fix missing labels on notifications page

- .github/main.workflow
GitHub now natively supports the deleting of branches from a repo's
settings screen so this workflow is not needed.
- Stale workflow
1. When this PR is merged, the `delete-branch-workflow` should be automatically deleted.
-
-
> Delete old branch workflow that is no longer used

- .github/workflows/tests.yml
The browser tests require Sauce credentials to be defined in GitHub repo settings (SAUCE_USERNAME and SAUCE_ACCESS_KEY). If these credentials aren't defined, the tests will fail. Unfortunately this means that if you have a fork without a Sauce account, you can't pass the test.
This change modifies the browser tests Action so that it won't run when on a fork. It would be better to somehow disable the tests only if those credentials aren't defined, but I couldn't find an easy way to do so.
> Don't run browser tests on forks

- CHANGELOG.md
Updates the changelog versions to match the numbers released on the applicable dates.
> Fix 'unreleased' releases in changelog

- docs/assets/css/netlify.less
- packages/cfpb-expandables/src/cfpb-expandables.less
Expand expandables when printing so that users get the entire page's content.
See https://github.local/CFPB/el-camino/issues/299
- Hide the netlify CMS floating buttons when printing because why not. They block the page text.
- Hide the `Show`/`Hide` buttons when printing because they're irrelevant (and if we left them, it'd incorrectly say `Show` above expandables that are now open when printed)
- Sets a large max-height when printing because we display the raw URLs next to links which causes the expandable's content height to be greater than the non-print height, causing this bug:
1. Visit the PR preview link below and view a print preview of the expandables page. They should all be expanded.
-
-
> Expand expandables when printing

- packages/cfpb-icons/src/icons-svg-inline.js
Plugin positon in the less plugins index will vary by the environment this file is built in, so we need to scan the plugins instead of having a hardcoded position.
- Make plugin index position dynamic.
1. `yarn build` should pass.
> Fix plugin path to remove hardcoding

- docs/pages/lists.md
- packages/cfpb-core/src/base.less
- Indents numbered lists 0.3rem to avoid clipping that can happen when lists are double digits. 
1. Check lists page in the design system on this PR preview link.
Before:
After:
> cfpb-core: Indent numbered lists

- docs/assets/js/redirect-banner.js
- docs/assets/js/sidebar.js
- packages/cfpb-atomic-component/src/utilities/type-checkers/index.js
- webpack.config.docs.js
IE11 does not like ES6 object shorthand. Instead of polyfilling all the places this is used, this PR just removes the shorthand.
- Remove ES6 object shorthand to support IE11 limitations.
1. PR tests should pass.
> Remove object shorthand to aid IE11

- docs/pages/text-inputs.md
- Adds date picker inputs to the DS.
1. See the text inputs page on the PR preview.
This has the bug where the input increases in width when first mousing over it. Let me know if you see a reason that is happening. It appears to be DS specific, since it doesn't happen in the blog filter in cf.gov.
> Add datepicker markup

- packages/cfpb-core/src/cfpb-core.less
- packages/cfpb-grid/src/cfpb-grid.less
The current paths to the normalize CSS works in the cf.gov repo, but breaks here. I think if we remove the path it'll just look into the `node_modules` where ever it's used.
- Update normalize paths
1. `gulp build` should pass.
> Update normalize paths

- docs/pages/dropdowns.md
- packages/cfpb-forms/src/molecules/form-fields.less
- packages/cfpb-forms/src/organisms/multiselect.less
Remove multiselects' horizontal scrollbar by hiding overflow-x and ensure content is never clipped by breaking long words to new lines with overflow-wrap.
See https://github.local/CFGOV/platform/issues/3290 and https://github.local/CFPB/el-camino/issues/346
The word wrapping is necessary because we sometimes use multiselects in very narrow columns and words like "Servicemembers" are longer than the width of the column:
1. Compare the [DS multiselect](https://cfpb.github.io/design-system/components/dropdowns-and-multiselects) with localhost or the PR preview at a variety of screen widths.
| <img width="339" alt="before" src="https://user-images.githubusercontent.com/1060248/99590247-1bfb2880-29bb-11eb-9cc6-1a8d3907e0a2.png">   | <img width="339" …
> Hide multiselect horizontal scroll, wrap checkbox label text

- docs/assets/css/color-swatches.less
- packages/cfpb-core/src/brand-colors.less
- Add beige family colors for seal
1. See specs on seal on https://cfpb.github.io/design-system/foundation/seal
2. Compare to same page on this PR's preview and see that beige colors are present.
> Add beige family colors for seal

- packages/cfpb-core/src/utilities.less
The multiselect [uses it](https://github.com/cfpb/design-system/blob/4c7f6970c0d44cd130703ef96259268b3b15d1e3/packages/cfpb-forms/src/organisms/Multiselect.js#L108) but it wasn't migrated from cf.gov. We haven't noticed its absence because the fieldset element has its height adjusted when it open/closes but it might be related to the latest Chrome bug we've discovered.
- `u-invisible` class
1. Nothing should look different.
-
-
> Add missing invisibility utility class

- docs/pages/tables.md
- packages/cfpb-atomic-component/src/components/AtomicComponent.js
- test/unit-test/src/cfpb-atomic-component/src/components/AtomicComponent-spec.js
- test/unit-test/src/cfpb-expandables/src/Expandable-spec.js
We have two syntaxes for specifying that a component is initialized. `data-bound` and `data-js-hook`. This PR changes the value to `data-js-hook` used elsewhere.
- Change data-bound to data-js-hook value
> Change data-bound to data-js-hook value

- packages/cfpb-forms/src/organisms/multiselect.less
- test/browser/packages/cfpb-forms.js
There's a regression w/ Chrome 87 that causes fieldset elements to not honor its layout properties. It causes multiselect options to overflow their fielset container. If you're on v87 locally you can see the bug by opening the multiselect at https://cfpb.github.io/design-system/components/dropdowns-and-multiselects
https://bugs.chromium.org/p/chromium/issues/detail?id=375693
https://codepen.io/contolini/pen/rNLXrvP
https://codepen.io/pembe180/pen/wCsIk
- Set the fieldset's display to `-webkit-box` for Chrome.
1. Compare the multiselect page in the PR preview against production in Chrome 87.
| <img width="679" alt="Screen Shot 2020-11-30 at 10 04 19 AM" src="https://user-images.githubusercontent.com/1060248/100626148-7073a180-32f3-11eb-9445-362b58cd0483 …
> Accommodate Chrome's improper handling of fieldset display properties

- packages/cfpb-forms/src/organisms/Multiselect.js
- test/browser/packages/cfpb-forms.js
While exploring the IE11 issue I discovered the cause is a larger issue with the multiselect not correctly filtering options.
- Pass the indices of the filtered options to the `_filterMatches` function.
1. Visit https://cfpb.github.io/design-system/components/dropdowns-and-multiselects and enter some text like "super" into the multiselect field. It should only display option 8 that contains the text "super". Instead, it shows everything but option 8.
1. Visit the PR preview link and verify it works as expected.
> Fix multiselect filtering

- packages/cfpb-forms/src/organisms/Multiselect.js
- test/unit-test/src/cfpb-forms/src/organisms/Multiselect-spec.js
This change properly handles multiselects defined with an `id` but not a `name`, as in [the example in the design system docs](https://cfpb.github.io/design-system/components/dropdowns-and-multiselects#multiselects-1).
```html
<select class="o-multiselect" id="something" multiple>
```
Currently, the JS code generates a text `<input>` with an empty `id` attribute. This means that the associated `<label>` points to the wrong thing, causing failures in accessibility audits, [for example](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1607472905780-28501.report.html).
Additionally, the current behavior fails to ensure that the generated checkboxes have unique `id`s, simply copying the option `value`s. This commit prepends each `id` with the enclosing `input` ID, …
> Ensure correct multiselect input labels and IDs

- packages/cfpb-forms/src/organisms/Multiselect.js
- packages/cfpb-forms/src/organisms/MultiselectModel.js
- test/browser/packages/cfpb-forms.js
The multiselect option IDs weren't being transferred to the removal buttons making it impossible to remove a selected option.
- Moves the `checkboxId` value to a property of `option` so that we can use it when rendering the selected options.
1. You should be able to remove selected multiselect options from this PR preview while you currently cannot at https://cfpb.github.io/design-system/components/dropdowns-and-multiselects
1. `yarn test:browser` should pass.
> Fix multiselect removal bug

- packages/cfpb-icons/src/icons-svg-inline.js
- URL encodes inline SVGs for IE11 support.
1. Visit the PR preview in IE11 in Sauce Labs and see that the inline background image SVGs are showing up on the dropdowns and in the checkboxes in the multiselect.
> Encode inline SVGs for IE11 support

- packages/cfpb-forms/src/organisms/Multiselect.js
- Listen for clicks of the selected item's button and pass that click down to the label it contains.
1. Visit the PR preview in IE11 in Sauce Labs and see that the multiselect's selected items can be removed.
> Multiselect: Pass clicks of the selected item's button down to the label it contains

- docs/_data/side-navigation.yml
- docs/_includes/variation-content.html
- docs/admin/config.yml
- docs/assets/css/main.less
- docs/assets/js/main.js
- docs/pages/transition-patterns.md
- packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
- packages/cfpb-expandables/src/ExpandableTransition.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/AlphaTransition-spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition-spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MoveTransition-spec.js
Transitions add an event listener that listens for the `transitionEnd` event, however, the element may have transitions that are performed outside of the transition class, making their `transitionEnd` event fire early and multiple times. To get around this, I've added a `CSS_PROPERTY` value that gets passed into the `BaseTransition` constructor, that is then checked in the `transitionEnd` handler when it fires.
- Adds transitions page and example code to design system.
- Adds `CSS_PROPERTY` value to transitions to pass to `BaseTransition` and associated logic.
- Updates transition tests to match those in cf.gov repo.
1. Check patterns > transition patterns in the PR's preview.
> Update transitions and add transitions page to DS

- packages/cfpb-atomic-component/src/utilities/transition/transition.less
- packages/cfpb-core/src/utilities.less
If you target an element directly with CSS class that has a `display: block` value and then add `u-hidden` to the element, it will be more general than the targeted CSS class and won't override the display value. I can't think of a scenario where we wouldn't want `u-hidden` to not set `display: none`. If that was not wanted, the class would instead be removed.
Additionally, the `u-no-animation` class sets `transition-duration` to zero in order to override the value set in the element's `transition` value set by either `u-move-transition` or `u-alpha-transition`. However, if the `u-no-animation` class is used to override an animation class that appears in another stylesheet to that of `transitions.less`, then the priority can be wrong and it will not override the animation duration. …
> Add important! to u-hidden and u-no-animation rules

- packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/MoveTransition-spec.js
`transitionEnd` event will not fire if the transition duration is zero, which leads to the `u-is-animating` class from not being removed. We therefore should manually called the transitionComplete event handler immediately if the `u-no-animation` class is present.
- When using a transition, call the transitionComplete event handler immediately if the `u-no-animation` class is present.
- Add test to check for proper removal of `u-is-animating` class if transition duration is zero.
> Transitions: Call transitionComplete handler if transition duration is zero

- docs/pages/iconography.md
This resolves #1136, where tables generated via markdown on the Iconography page were not expanding to the full width of their container. Someone had attempted to fix this before by creating an `icon-table` class, but because Markdown spacing is finicky the class wasn't being applied. To properly apply the class one line of space should come between the table markup and the `{: class="icon-table"}` class signifier.
For example:
```md
| icon                                | icon-round                                | canonical name | aliases       |
| ----------------------------------- | ----------------------------------------- | -------------- | ------------- |
| {% include icons/up.svg %}          | {% include icons/up-round.svg %}          | up             | chevron-up    |
| {% …
```
> Make Iconography tables full width of container

- packages/cfpb-atomic-component/src/utilities/atomic-helpers.js
`InstantiateAll` was checking for the existence of the `data-js-hook` attribute, instead of checking its value, meaning it would be prevented from creating new instances if a component already had the `data-js-hook` attribute, but had not yet been initialized.
- Makes `instantiateAll` check `data-js-hook` value instead of only the existence of the attribute.
1. Hard to test till it's released, but it could be used at https://github.com/cfpb/consumerfinance.gov/pull/6206#discussion_r556570024
> InstantiateAll: Check for value in data-js-hook as opposed to existence of attribute

- packages/cfpb-atomic-component/src/utilities/atomic-helpers.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers-spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/data-hook-spec.js
- Add unit test spec for `data-hook.js`.
- Adjust data-hook import to import specific methods.
- Add additional `instantiateAll` test.
1. `gulp test:unit` should pass.
> Add unit test for data-hook and instantiateAll

- docs/pages/variables.md
- packages/cfpb-buttons/src/cfpb-buttons.less
- packages/cfpb-buttons/usage.md
Fixes [GHE]/CFGOV/platform/issues/3915
- Darkens red warning text buttons.
1. Visit the buttons page in the PR preview and check the "Destructive action" example and compare to https://cfpb.github.io/design-system/components/buttons
> Buttons: Darken red warning button text

- packages/cfpb-core/src/base.less
- Changes table headers from H5 to paragraph medium, sentence case, and top-aligning the baseline.
1. Check tables page in this PR and compare table headers to https://cfpb.github.io/design-system/components/tables
Before:
After:
> Tables: Adjust table header style

- packages/cfpb-forms/src/organisms/Multiselect.js
- packages/cfpb-forms/src/organisms/MultiselectUtils.js
- test/unit-test/src/cfpb-forms/src/organisms/MultiselectUtils-spec.js
For every selection of a multiselect item, the stored list of option data is iterated over for a match. This PR places an attribute on the `inputs`, `data-index`, which records their original index position in the underlying `<select>` element. In the future maybe we can pass this index around within the multiselect and not require storing it in the dom, but this gets rid of the search step through removal of the `indexOfObject` utility.
- Multiselect `indexOfObject` utility.
- Store checkbox input's index position within a `data-index` attribute in the markup.
1. Check dropdowns and multiselects page on the preview PR. The multiselect should be able to add and remove options same as before.
> Multiselect: Remove indexOfObject utility

- packages/cfpb-atomic-component/src/utilities/transition/transition.less
- packages/cfpb-buttons/src/cfpb-buttons.less
- packages/cfpb-core/src/vars.less
- packages/cfpb-expandables/src/cfpb-expandables.less
- packages/cfpb-forms/src/atoms/select.less
- packages/cfpb-forms/src/cfpb-forms.less
- packages/cfpb-layout/src/cfpb-layout.less
- packages/cfpb-notifications/src/cfpb-notifications.less
- packages/cfpb-notifications/src/organisms/banner.less
- packages/cfpb-pagination/src/cfpb-pagination.less
- packages/cfpb-tables/src/cfpb-tables.less
- packages/cfpb-typography/src/cfpb-typography.less
`gulp build` was not passing because the `transitions.less` file needs a variable from `vars.less`. `vars.less` needs a variable from `brand-colors.less`.
- Move imports to top of file.
- Changes to absolute imports.
- Add reference import to `brand-colors.less` inside `vars.less`.
1. `gulp build` should pass.
2. DS PR preview should be unchanged from production.
> Move imports to top and changes to absolute imports

- packages/cfpb-forms/src/organisms/Multiselect.js
- packages/cfpb-forms/src/organisms/MultiselectModel.js
- test/unit-test/src/cfpb-forms/src/organisms/MultiselectModel-spec.js
`_optionsData` array is in `MultiselectModel` and `Multiselect`. It should only be in `MultiselectModel`.
- Remove `_optionsData` array from `Multiselect`.
- Includes `data-index` attribute from https://github.com/cfpb/design-system/pull/1176
1. Check dropdowns and multiselects page on the preview PR. The multiselect should be able to add and remove options same as before.
> Multiselect: Remove redundant _optionsData array

- packages/cfpb-forms/src/atoms/label.less
`.a-label__heading` is designed to function as an `h4` (via its call to the `.heading-4` mixin) but doesn't respond to small screens [like an `h4`](https://github.com/cfpb/design-system/blob/main/packages/cfpb-core/src/base.less#L250-L256). This PR fixes that.
> Makes a-label__heading respond like an h4 on small screens

- packages/cfpb-forms/src/organisms/Multiselect.js
- packages/cfpb-forms/src/organisms/multiselect.less
When you open the multiselect, let's make it so the down-arrow on the right-hand side closes it when clicked, yaaay! Also, let's flip the arrow when it is open! Yaaaah!
- Make clicking the arrow in the search input open AND close the drop-down.
- Switch the drop-down arrow to an up arrow when the drop-down is open.
1. Open the PR preview and go to the dropdowns and multiselects page and open and close the multiselect by clicking the arrow.
> Multiselect: Make arrow open/close drop-down

- packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
If the window size is changing, we may need to recalculate the `max-height` of an element. This PR adds `refresh` method that does this re-calculation of the `max-height`.
- Add `refresh` method to `MaxHeightTransition` for re-calculating the inline `max-height` of the element.
1. No changes here. It'll get used in cf.gov.
> MaxHeightTransition: Add refresh method

- packages/cfpb-forms/src/organisms/multiselect.less
- Adds padding to max selections view of drop-down.
- Adds `pointer-events: none` to max selections view, so that clicking the drop-down closes it.
1. In PR preview open multiselects page and interact with multiselect to select five options. Max selections view should have padding and close when clicked.
- Arrow doesn't work to close the drop-down (on max selection view) as we don't have a good way yet to know when the drop-down is completely open.
> Bugfix: multiselect missing padding on max selection

- packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/transition.less
Probably best to show a fixed height for the summary, regardless on base font size. This changes the max-height to pixels from ems, and match the value set in the Summary component https://github.com/cfpb/consumerfinance.gov/blob/c1bc097d598ffae6f1c2215e1bcac3c057f972d1/cfgov/unprocessed/js/organisms/Summary.js#L45
- Change `u-max-height-summary` `max-height` to pixels from ems.
- Set the `max-height` on the element when the page has fully loaded, as the reported value from `scrollHeight` may be incorrect before then.
1. max-height transition on the /design-system/patterns/transition-patterns page in the PR preview should work as before.
2. Change the font-size in the Chrome settings and reload the page. See that the box is the same height, whereas on …
> MaxHeightTransition: Convert summary transition to px from ems

- packages/cfpb-forms/src/organisms/Multiselect.js
If the multiselect's underlying select element has a `name` attribute set, the search input field `id` becomes that name. However, on pages such as https://www.consumerfinance.gov/about-us/blog/, the Topic filter `for` attribute is expected to point to the `id`, not the `name`. 
- Sets the search input to be the `id` value of the underlying `select` element, instead of the `name` attribute, if present.
1. Check the PR preview and visit the multiselect page and see that you can click the label above the multiselect and see that it activates the search input.
> Multiselect: Change search input ID to DOM ID

- docs/pages/variables.md
- packages/cfpb-typography/src/cfpb-typography.less
- packages/cfpb-typography/usage.md
This improves the accessibility of jump links on mobile by increasing the contrast between the foreground text and background color.
Fixes #1201.
> Change mobile jump link background to @gray-5

- docs/pages/carousel.md
The carousel anti-pattern page currently fails Lighthouse accessibility testing because it lacks an h2:
"Heading elements are not in a sequentially-descending order"
This causes the nightly Lighthouse tests to fail, for example:
https://github.com/cfpb/design-system/actions/runs/612274827
> Add variation group name to fix missing h2

- packages/cfpb-design-system/src/cfpb-design-system.js
cfpb-design-system.js includes requires for modules instead of imports, which makes it unusable.
- Change incorrect requires to imports in cfpb-design-system.js
> Fix imports in cfpb-design-system.js

- docs/assets/css/variation.less
Editors of the DS website use markdown tables to organize content side-by-side. The HTML tables generated by the markdown are often unreasonably narrow because none of their inner content has a width specified.
I'm not modifying our .o-table organism because I only want to force tables to be full-width on the DS website, and not across cf.gov.
Fixes https://github.com/cfpb/design-system/issues/1239
1. The [landing pages page](https://cfpb.github.io/design-system/pages/landing-pages) of the PR preview should have non-squished tables.
> Expand DS documentation tables to full width

- packages/cfpb-expandables/src/cfpb-expandables.less
Expandables' overflow is hidden to prevent their contents from spilling
outside their containers when collapsing. A side effect is that UI elements
that *should* be allowed to spill outside their containers  (like multiselect
dropdowns) are unable to do so. The solution is to only hide overflow during
the collapsing animation.
This will allow us to convert cf.gov's filterable list controls checkboxes into multiselects.
- Expandables' contents' overflow.
1. PR tests should pass.
2. Nothing visual should change at the PR preview [expandables page](https://cfpb.github.io/design-system/components/expandables).
| before (overflow hidden all the time) | after (only hidden during animation) |
|--------|--------|
| ![before](https://user-images.githubusercontent.com/1060248/122793647-729a4f00-d289 …
> Only hide expandable content during animation

- packages/cfpb-forms/src/molecules/form-fields.less
- packages/cfpb-forms/src/organisms/form.less
Field-level error messages are meant to have a [15px margin between the field with the error and the message](https://cfpb.github.io/design-system/components/notifications#error-notification-field-level). That margin was only present [when the error message was in an `.m-form-field container`](https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/molecules/form-fields.less#L241-L244). Our [text input with button pattern](https://cfpb.github.io/design-system/components/text-inputs#text-input-with-a-button) (where the text field and the button are on the same line) don't have the `.m-form-field` wrapper, so error messages in those kinds of forms had no top margin.
- Add top margin to field-level notifications in text input with button forms
Whip up a test case that puts a …
> Fix field-level error message margins

- packages/cfpb-forms/src/atoms/text-input.less
The pacific focus state of our text inputs overrides any modification
colors for error/warning/success. This means that if an input field
is modified while the user is actively focused on it, they won't receive
visual feedback that something has changed.
- Hover/focus states to text input modifiers.
1. Compare the three production [modified text inputs](https://cfpb.github.io/design-system/components/notifications#warning-notification-field-level) to the [PR preview](https://deploy-preview-1257--cfpb-design-system.netlify.app/design-system/components/notifications#warning-notification-field-level). Also compare them to the [default text inputs](https://cfpb.github.io/design-system/components/text-inputs).
-
-
> Maintain text input modifier colors on focus/hover

- docs/assets/css/sidebar.less
Follow up to https://github.com/cfpb/design-system/pull/1259 to fix issue where margin was missing on desktop third-level items in the sidebar.
- Add bottom margin to nav last item on desktop/tablet only (not mobile).
1. Check the PR preview pages like https://cfpb.github.io/design-system/patterns/ that have three levels of items and ensure they're correct on desktop and mobile.
> DS website: Update sidebar to add bottom margin to menu items at desktop/tablet

- docs/assets/js/main.js
https://github.com/cfpb/design-system/pull/443/ exempted live code examples from anchor linking, but targets `live-code-example` while the live code blocks use `a-live_code` as changed in https://github.com/cfpb/design-system/pull/466/. Erroneous links appear within the code examples as seen on https://cfpb.github.io/design-system/patterns/cards
- Change anchor linking to fix class name.
1. Visit the cards pattern and see that there is no anchor link in the links within the card patterns.
> Anchor linking: Fix live code example

- docs/assets/css/toggle-code-button.less
The toggle code CSS includes a redundant `u-hidden` declaration (see https://github.com/cfpb/design-system/pull/466#discussion_r418563532). However, `u-hidden` has `!important` now (see https://github.com/cfpb/design-system/pull/1138) so the re-declaration is not necessary. 
- Removes redundant `u-hidden` declaration.
1. Visit a component page in the PR preview and see the SHOW/HIDE details toggle works as expected.
> Remove unnecessary u-hidden

- docs/pages/video.md
Lighthouse tests currently fail on the video page due to missing titles on the (hard-coded) video iframes. This commit adds titles to them.
[Here's](https://github.com/cfpb/design-system/runs/3335572033?check_suite_focus=true) an example of a failing nightly Lighthouse run. With this change, Lighthouse now scores the video page 100% for accessibility:
> Add title attributes to video iframes

- docs/_includes/variation-content.html
- docs/admin/config.yml
- docs/assets/css/variation.less
We will be updating the card patterns as we develop a new homepage, however, both the old and new patterns will need to remain in the design system as we develop the new homepage. When it's switched over to the new page we'll be able to remove the old ones in the design system. This feature adds a toggle to the DS netlify admin to flag a variation pattern as "deprecated" so we know to not reference it anymore and that it is slated for deletion.
- Add "is deprecated" toggle to individual variations.
1. Edit a page in the PR preview and find the "is deprecated" toggle in the variation and turn it on to see the "DEPRECATED" label show up next to the name.
> Add deprecate toggle to variations

- docs/pages/wells.md
- packages/cfpb-layout/src/organisms/wells.less
The new homepage uses a new well call an inkwell that has a dark gray background.
- Adds inkwell pattern.
1. Check out the wells page in the PR preview.
> Add inkwell organism

- docs/pages/dropdowns.md
- packages/cfpb-forms/src/organisms/Multiselect.js
- packages/cfpb-forms/src/organisms/MultiselectModel.js
It was possible to select infinite options in the multiselect if the multiselect was loaded with the max selection count. This PR fixes that loophole.
- Changes multiselect model to stop checking options after the maximum selection number has been reached.
- Changes multiselect to initialize the model before populating the markup and to check the model for the selections.
- Updates the multiselect example in the DS docs to load with the maximum selection to begin with.
1. Check the multiselect in the PR preview and add and remove items to see that it works.
2. If you really want to thoroughly vet this, pull the branch and run a local server and change the number of items in dropdowns.md that have the `selected` attribute so-as to change the number of items the multiselect has on page …
> Fix multiselect infinite selections bug

- packages/cfpb-layout/src/molecules/card.less
- Set a white background on topic cards so they don't have a transparent background.
1. Check cards page in the PR preview and compare to https://cfpb.github.io/design-system/patterns/cards
> Cards: Set a white background on topic cards

- packages/cfpb-layout/src/molecules/card.less
- packages/cfpb-layout/src/organisms/wells.less
Fixes https://github.com/cfpb/design-system/issues/1300
- Adds a utility for setting all the states of the cards and darkens the highlight card link text to be an accessible contrast.
1. Visit the cards page in the PR preview and check for contrast accessibility errors.
> Cards: Make highlight card colors accessible

- docs/pages/taglines.md
The current [taglines page](https://cfpb.github.io/design-system/patterns/taglines) fails Lighthouse accessibility due to a missing `<h2>`. See example Lighthouse run [here](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1632961839718-84104.report.html):
This commit adds a variation group name so that we get the missing `<h2>`; I used the name "Types" since that's what we seem to use elsewhere, for example on the [Cards](https://cfpb.github.io/design-system/patterns/cards) page.
> Update "taglines" page

- docs/pages/taglines.md
- packages/cfpb-typography/src/atoms/tagline.less
Preference is to have the tagline stack under 600px only when the extra-large size is used.
- Taglines: Move stacking to only affect xtra-large size
1. Visit taglines PR preview page and resize to mobile and see that only the extra-large size stacks with the flag on its own line.
> Taglines: Move stacking to only affect extra-large size

- packages/cfpb-notifications/src/molecules/notification.less
Notification explanation was acquiring a bottom margin from the `<p>` element, however, if the notification explanation is not a paragraph the bottom margin would be lost. This PR adds the bottom margin to the `m-notification_explanation` element so that it is present, regardless of the HTML tag of the element.
- Adds margin-bottom to notification explanation.
1. Visit the notification page in the PR preview.
2. Resize to mobile.
3. Inspect the notification and look at the `m-notification_explanation` and see it has a margin bottom that overrides the same value in the `p` element.
> cfpb-notifications: Add margin-bottom to notification explanation

- Gemfile
- _config.yml
- docs/pages/accessibility.md
Redirect https://cfpb.github.io/design-system/guidelines/accessibility
to
https://cfpb.github.io/design-system/guidelines/accessibility-principles
- Added `gem 'jekyll-redirect-from'` plugin to redirect
1. Put /design-system/guidelines/accessibility in URL and test if it redirects to new accessibility page
Resolves https://github.com/cfpb/design-system/issues/1324
> Redirect to new accessbility URL

- packages/cfpb-layout/src/organisms/wells.less
Wells have borders. Inkwells have borders. Inkwells shouldn't have borders.
- Remove inkwell border.
1. Compare PR preview to http://localhost:4000/design-system/patterns/wells#inkwell and see that inkwell doesn't have a border anymore.
> Inkwell: Remove border

- docs/pages/accessibility.md
Redirect https://cfpb.github.io/design-system/accessibility
to
https://cfpb.github.io/design-system/guidelines/accessibility-principles
- Added another redirect for accessibility page
1. Put /design-system/accessibility in URL and test if it redirects to new accessibility page
Further resolves https://github.com/cfpb/design-system/issues/1324
> Implemented another redirect for accessibility page

- packages/cfpb-layout/src/organisms/wells.less
- packages/cfpb-typography/src/atoms/tagline.less
- Give the tagline a max-width inside inkwells.
- Increase the tagline gap between icon and text at the extra large size.
- Increase the font-size of the tagline at the extra large size.
1. Compare PR preview tagline to https://cfpb.github.io/design-system/patterns/taglines#extra-large-tagline and https://cfpb.github.io/design-system/patterns/wells#inkwell
Before:
After
:
> Tagline: Adjust font-size, icon-text spacing, and max-width in inkwell

- docs/pages/heroes.md
#1299 modified the content of the heroes page and added several examples with `<h1>` tags. This [breaks Lighthouse accessibility checking](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1635899316291-28563.report.html), with then fails with "Heading elements are not in a sequentially-descending order". To fix this, this commit changes those `<h1>` tags to be `<p class="h1">`.
This was also how the previous hero content was configured in f3085f2831fc377307987bf0c7b42c56d0063827.
Edit: preview altered page at https://deploy-preview-1328--cfpb-design-system.netlify.app/design-system/patterns/heroes; this now scores 100 on Lighthouse.
> Fix broken heading order on heroes page

- docs/pages/typography.md
It looks like an empty link was inadvertently added to the typography page in #1341.
> Remove empty link from typography page

- packages/cfpb-core/src/base.less
This was pulled from an [enhancement in cf.gov](https://github.com/cfpb/consumerfinance.gov/blob/8660b3a845f8dc983c951ab45ae125366a180743/cfgov/unprocessed/css/enhancements/base.less) but belongs here.
> Make nav links unstyled by default

- packages/cfpb-buttons/src/atoms/buttons-with-icons.less
- packages/cfpb-forms/src/atoms/select.less
- packages/cfpb-forms/src/molecules/form-fields.less
- packages/cfpb-icons/src/cfpb-icons.less
- packages/cfpb-layout/src/cfpb-layout.less
- packages/cfpb-layout/src/organisms/featured-content-module.less
We ship css to all our users that is only targeting browsers that are sub-0.5% usage. This is wasteful and blocking for people on slow connections and mobile phones with slower processing speeds (which are a much greater proportion of our users that ie8, ie9, and ie10).
Thus, this removes those classes. There will be another PR coming in https://github.com/cfpb/consumerfinance.gov to match this behavior and remove modernizr (which was only really used by the `.no-csspointerevents` class here).
> Pull old ie support

- packages/cfpb-core/src/media-queries.less
- packages/cfpb-forms/src/organisms/form.less
- packages/cfpb-layout/src/cfpb-layout.less
- packages/cfpb-layout/src/molecules/heroes.less
- stylelint.config.js
- Stylelint: Ignore less/color-no-invalid-hex and less/no-duplicate-variables rules and remove ignore comments.
1. `yarn run gulp lint:styles` should have no errors.
> Stylelint: Ignore less/color-no-invalid-hex and less/no-duplicate-variables rules

- stylelint.config.js
- Remove unneeded stylelint rules
1. `yarn run gulp lint` should pass without errors.
> Remove unneeded stylelint rules

- packages/cfpb-grid/src/cfpb-grid.less
Tiny addendum to https://github.com/cfpb/design-system/pull/1358
- Add needed missing parentheses to `percentage(…)` mixin.
1. `yarn build` should pass.
> Fix percentage parentheses for Less 4.x compatibility

- docs/assets/css/main.less
- docs/pages/variables.md
- packages/cfpb-typography/src/cfpb-typography.less
- packages/cfpb-typography/src/licensed-fonts.less
- packages/cfpb-typography/usage.md
With fonts being shipped in cf.gov, we no longer need this variable or the associated logic.
> Remove @use-font-cdn variable and logic

- packages/cfpb-forms/src/organisms/form.less
Currently our "text input with a button" pattern looks as follows:
However, everywhere this is used in cf.gov, we specifically add styles that make the button flush with the input, like this:
This brings that behavior into the design-system. After merge and release, a follow-on PR to cf.gov will remove all that soon-to-be unneeded customization.
> Centralize text input with a button pattern in the design system

- packages/cfpb-forms/src/organisms/Multiselect.js
Our Cypress functional tests currently get elements by id or classname. By adding data-cy attributes, we can easily retrieve elements, and be sure that what we are searching those elements out by will not change.
- Added a data-cy attribute to multiselect options
1. Ensure data-cy element is added to multiselect options
> add data-cy attribute to multiselect options

- docs/pages/banners.md
- packages/cfpb-notifications/src/organisms/banner.less
As part of our 1071 work, we'll be using banners to indicate the status of our online filing guide. Our default gold banner will be used to flag outdated versions of the guide, while a more eye-catching dark teal banner will highlight super old archived versions.
- Dark banner variation
1. Check it out at https://deploy-preview-1387--cfpb-design-system.netlify.app/design-system/components/banners
> Add new dark banner variation

- docs/pages/banners.md
This fixes an accessibility error that Lighthouse discovered.
Without this change, the heading order goes h1, h3.
This adds the missing h2.
> Add variation group name to Banners page

- docs/pages/heading-hierarchy.md
- packages/cfpb-core/src/base.less
- packages/cfpb-layout/src/molecules/heroes.less
This PR institutes changes to our type hierarchy, specifically the weight of our H1 and H2.
@ajbush has been running point on the design part of this change, so he can field design-related questions. I can handle any technical requests!
- Change H1, H2 weight to 600
> Hierarchy changes

- docs/pages/expandables.md
- docs/pages/filterable-list-control-panels.md
- docs/special-pages/updating-this-website.md
- packages/cfpb-expandables/src/cfpb-expandables.less
- packages/cfpb-expandables/usage.md
- test/unit-test/src/cfpb-expandables/src/Expandable-spec.js
Fixes https://github.com/cfpb/design-system/issues/1398
- Converts expandable header from a float to a flexbox layout.
1. `yarn start` and view http://localhost:4000/design-system/components/expandables and resize the window and expand/collapse the expandables.
Before:
After:
> Convert expandable header to flexbox

- packages/cfpb-expandables/src/cfpb-expandables.less
This is needed for an expandable in the rural and underserved populations app.
- Update cfpb-expandables.less to include `justify-content: space-between;`
1. Check the expandables page in the PR preview and see that the expandables toggle is unchanged.
> Update cfpb-expandables.less to include `justify-content: space-between;`

- packages/cfpb-expandables/src/cfpb-expandables.less
If an expandable has a very long header text, the toggle will wrap. This change sets a min-width on the toggle so it doesn't wrap, and also right aligns the text so the toggle aligns between the show and hide text.
- Set a min-width for expandable toggles.
1. Visit the PR preview and edit the header text for an expandable to a really long string and see how the toggle responds.
Before:
After:
> Set a min-width for expandable toggles

- .gitignore
- docs/assets/css/main.less
- package.json
- scripts/fonts.sh
https://github.com/cfpb/design-system/pull/1370 removed the fonts cdn logic, but we still need to install the fonts to be served on the site.
- Add fonts.sh script 
- Runs font download script on postinstall
1. PR Checks should pass and PR preview should not have 404s for the fonts.
> Add fonts.sh script

- .github/workflows/publish.yml
- scripts/fonts.sh
Oops the curl commands here for the fonts were incorrect and were downloading zero kb files!
- Fixes curl command URLs and flags to be correct in fonts.sh script.
- Reverts https://github.com/cfpb/design-system/pull/1429
- PR checks should pass.
- Running ./scripts/fonts.sh should produce font files that have a file size.
> Fix font.sh curl commands 

- docs/pages/conducting-research-3.md
The [Conducting Research page](https://cfpb.github.io/design-system/guidelines/conducting-research) currently has an empty link that points to a non-existing bookmark (note "harmful todraw"):
When the page [was first created](https://github.com/cfpb/design-system/commit/a7f05aa5a37c07a68892a5b76d5c6a1fdb55330e#diff-9f71e1d32f07f2458729149d0ab03d428cf4d8a10424439f8e3ee7628e98cc8dR23), the word "harmful" linked to an "Identify hazards and" bookmark. This link was seemingly removed [during the editing process](https://github.com/cfpb/design-system/commit/ea4493eb510d02a9fbcbaa0b36d2ca5bd3472cab#diff-9f71e1d32f07f2458729149d0ab03d428cf4d8a10424439f8e3ee7628e98cc8dR23) but an empty link was left behind, perhaps due to a Netlify CMS issue.
This empty link fails the Lighthouse accessibility …
> Remove empty link from Conducting Research

- docs/admin/src/widgets/StringTrimmed.js
- docs/admin/src/widgets/StringWithInstructions.js
Refactors two react classes to use functional components instead of class components, per #1423.
- Refactors `StringTrimmedControl` to use functional components instead of class components.
2. Any regressions should show up in the netlify preview.
- I'm new to some of these libraries, so apologies if I'm doing something non-idiomatic. (Please let me know, if so!)
- There are three more class components in `admin/src/widgets`, which I'm planning on handling in a subsequent PR.
> Convert two react class components to functional components

- netlify.toml
- package.json
Netlify settings and script had differing node versions. This sets both to the latest 16.x version
- Set same node version for netlify settings.
> Set same node version for netlify

- README.md
Relevant https://github.com/cfpb/design-system/issues/415
- Adds Ruby installation section for runing the DS site locally.
1. Read the instructions. Comment on any issues.
> Add ruby install instructions

- docs/pages/tables.md
- packages/cfpb-tables/src/cfpb-tables.less
Our responsive table styles are [duplicated in cf.gov](https://github.com/cfpb/consumerfinance.gov/blob/2ace1532d9b24595db6b436f008f02cc7e03ae19/cfgov/unprocessed/css/enhancements/tables.less#L125-L170). This PR consolidates them in the DS and a subsequent PR will remove them from cf.gov.
Also, printing a page triggers our smallest 600px breakpoint, causing our mobile styles to be applied. This is fine for most of our design patterns but it provides a degraded experience on pages with HTML tables. The responsive table media query has been updated to only apply to `screen` media types and not `print`.
See https://github.local/CFPB/1071-data-collection/issues/317#issuecomment-326594
- Consolidated our responsive tables styles from cf.gov.
- Tables are not responsive with `print` media …
> Consolidate cf.gov responsive table styles, ignore print media

- packages/cfpb-atomic-component/README.md
- packages/cfpb-atomic-component/src/components/AtomicComponent.js
- packages/cfpb-atomic-component/src/utilities/dom-traverse.js
- packages/cfpb-atomic-component/src/utilities/type-checkers.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/type-checkers.spec.js
If the type checkers don't use a default export we can import the individual checkers where needed, which seems better.
- Remove default export from type-checkers
> Remove default export from type-checkers

- docs/assets/js/search.js
- packages/cfpb-icons/src/icons-svg-inline.js
Oops this should be an import not a require in an esm world.
- Change to an import for lunr search package.
1. PR preview search should work.
> Fix broken require to lunr in search

- packages/cfpb-icons/src/icons-svg-inline.js
Fixes issue where https://github.com/cfpb/design-system/pull/1505 broke `yarn start`
> Downgrade to commonjs syntax in less plugin

- package.json
https://github.com/cfpb/design-system/pull/1532 made `yarn` or `yarn install` not automatically run `postinstall` (since it was renamed), so `after-install` needs to instead be manually run after `yarn`. This PR adds that in the `build-netlify` step, which had been calling `yarn`.
- Add after-install command to build-netlify yarn command
> Add after-install command to build-netlify yarn command

- .editorconfig
cfgov uses 2 spaces for CSS (updated in https://github.com/cfpb/consumerfinance.gov/pull/7009). This PR changes the editorconfig to use 2 spaces, since we do that already in e.g. https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/organisms/multiselect.less
- Change all indenting to 2 space
> Editorconfig: Change all indenting to 2 space

- packages/cfpb-forms/src/organisms/multiselect.less
@wpears [fixed this bullet on cfgov](https://github.com/cfpb/consumerfinance.gov/pull/7205), but I just noticed we have a duplicate `multiselect.less` in cfgov and the design-system and the edit never made it over here. 
- Hide bullet on the multiselect.
1. In the PR preview, visit the multiselect and add five items and there shouldn't have a bullet. The bullet looks like this:
> Hide bullet on multiselect dropdown

- docs/assets/css/main.less
- docs/assets/js/main.js
- docs/pages/transition-patterns.md
- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
- packages/cfpb-atomic-component/src/utilities/behavior/behavior.js
- packages/cfpb-atomic-component/src/utilities/transition/transition.less
- test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.spec.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/behavior.spec.js
Moves mature code from cfgov to DS.
- Add FlyoutMenu behavior and add to transitions page. 
1. Visit /design-system/patterns/transition-patterns in the PR preview and scroll to the bottom and ensure the example works.
> Add FlyoutMenu behavior to DS

- packages/cfpb-buttons/src/atoms/buttons-with-icons.less
- packages/cfpb-buttons/src/cfpb-buttons.less
- packages/cfpb-buttons/src/molecules/button-groups.less
- packages/cfpb-expandables/src/cfpb-expandables.less
- packages/cfpb-forms/src/cfpb-forms.less
- packages/cfpb-layout/src/cfpb-layout.less
- packages/cfpb-notifications/src/cfpb-notifications.less
- packages/cfpb-pagination/src/cfpb-pagination.less
- packages/cfpb-typography/src/cfpb-typography.less
- Remove unneeded imports in cfpb-buttons.
- Change imports to references.
1. PR preview should show no visual CSS changes.
> Remove unneeded less imports

- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
- packages/cfpb-atomic-component/src/utilities/behavior/behavior.js
- packages/cfpb-forms/src/organisms/Multiselect.js
- Remove linting ignore comments that are not being applied.
- Ignore `no-use-before-define` in some cases.
- Update transition comment to be parent transition `BaseTransition`.
1. PR checks should pass. `yarn lint` should pass.
> Ignore some linting rules

- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
- packages/cfpb-atomic-component/src/utilities/transition/AlphaTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/MaxHeightTransition.js
- packages/cfpb-atomic-component/src/utilities/transition/MoveTransition.js
If you have only a collapse transition, or an expand transition, then the transition completion events won't fire since there's no state to expand or collapse from.
- Add `proxyEvents` method to BaseTransition to pass its events through to its child transitions.
- Transitions: Enforce having both expand and collapse transitions.
> Transitions: Enforce having both expand and collapse transitions

- docs/_data/side-navigation.yml
- docs/assets/js/main.js
- docs/pages/summaries.md
- packages/cfpb-core/src/breakpoint-state.js
- packages/cfpb-expandables/src/Summary.js
- packages/cfpb-expandables/src/cfpb-expandables.less
- packages/cfpb-expandables/src/summary.less
- test/unit-test/src/cfpb-expandables/src/Summary-spec.js
Add summary component and breakpoint-state from cfgov repo.
- Add summary component.
- Add breakpoint-state.js to cfpb-core.
1. PR preview should have a Summaries page, which when resized to mobile should have two summary buttons.
> Add Summary component

- packages/cfpb-notifications/src/molecules/notification.less
- Adds padding adjustments for right-to-left layouts (RTL), which currently is only arabic.
1. You'll need to copy the notification.less file from here into cfgov's node_modules/@cfpb/cfpb-notifications/src/molecules/notification.less and `yarn build` in cfgov.
2. In cfgov, visit http://localhost:8000/language/ar/coronavirus/mortgage-and-housing-assistance/renter-protections/emergency-rental-assistance-for-renters/ and see that the notification looks ok. 
Before:
After:
> cfpb-notifications: Update notification.less to support arabic rtl layout

- docs/assets/css/netlify.less
The edit buttons could appear under content, if the content's z-index was greater than 1. This PR increases the edit button's z-index to 100.
- Increase netlify edit button's z-index to 100.
> Increase netlify admin button z-index to 100

- packages/cfpb-forms/src/organisms/Multiselect.js
- test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/behavior.spec.js
- test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
- test/unit-test/src/cfpb-forms/src/organisms/Multiselect.spec.js
- test/util/simulate-event.js
See [GHE]/CFGOV/platform/issues/4391
- Unit tests: Migrate deprecated keyCode to KeyboardEvent.key.
- Mulltiselect: Migrate deprecated keyCode to KeyboardEvent.key.
- Mulltiselect: Move constants outside of instance.
1. PR checks should pass. Multiselect should work as before.
> Migrate deprecated keyCode to KeyboardEvent.key

- packages/cfpb-forms/src/organisms/Multiselect.js
https://github.com/cfpb/design-system/pull/1524 left a `inside` attribute on the Multiselect's list.
- Remove unneeded `inside` attribute on Multiselect's "choices" unordered list.
1. Inspect the markup of the multiselect in the PR preview and see that it doesn't have an `inside` attribute.
Before:
> cfpb-forms: Remove erroneously `inside` attribute left in Multiselect

- packages/cfpb-expandables/src/summary.less
- Summary: move padding to prevent clipping focus rectangle
1. Visit http://localhost:4000/design-system/components/summaries# and ensure that the focus area on a link rectangle within a summary is not clipped.
> Summary: move padding to prevent clipping focus rectangle

- packages/cfpb-typography/src/molecules/list.less
- cfpb-typography: Remove right padding from RTL lists
1. You'll need to copy the list.less file from here into cfgov's node_modules/@cfpb/cfpb-typography/src/molecules/list.less and `yarn build` in cfgov.
2. In cfgov, visit http://localhost:8000/language/ar/coronavirus/mortgage-and-housing-assistance/help-for-homeowners/learn-about-forbearance/ and see that the info units links are aligned with the right-hand edge. 
Before:
After:
> cfpb-typography: Remove right padding from RTL lists

- .stylelintrc.cjs
- docs/assets/css/code.less
- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
- packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
- packages/cfpb-expandables/src/summary.less
- packages/cfpb-layout/src/molecules/card.less
- test/unit-test/src/cfpb-atomic-component/src/utilities/transition/BaseTransition.spec.js
https://github.com/cfpb/design-system/pull/1581/ updated stylelint and ran some autolinting, which turned a gradient to yellow. This reverts the gradient change and autofixes some other issues.
- Remove `hyphens`, `tab-size`, and `::selection` browser prefixes from code.less.
- Revert to use `stylelint-config-prettier` for now.
- Reverts gradient syntax change.
- Autofixes other issues.
> Fix stylelint config

- packages/cfpb-forms/src/organisms/Multiselect.js
- Downcase `selectionsupdated` event to match native event formatting.
- Fix event dispatch to be `collaspebegin` instead of `expandend`
> cfpb-forms: downcase event and fix event dispatch

- packages/cfpb-atomic-component/src/utilities/transition/BaseTransition.js
`u-is-animating` class was set on the transition element, regardless of whether it was animating or if the completion handler was called right away, which led to cases where `u-is-animating` was stuck on the element after it was done transitioning. This PR sets it so it only is set when the element is actually animating.
- Don't set u-is-animating if transitionComplete handler is called right away
> cfpb-atomic-component: Don't set u-is-animating if transitionComplete handler is called right away

- docs/pages/e-mail-signup-forms.md
- packages/cfpb-layout/src/organisms/email-signup.less
We can remove much of the margin settings in the email signup organism by using the `gap` property. Also, we gain no use of `m-btn-group`, other than introducing styles we need to override. So, we should create an element specific to the email signup, which I'll call `o-email-signup_buttons`.
- Use `gap` property so that margin settings can be removed.
- Change `m-btn-group` to `o-email-signup_buttons`.
1. Visit https://deploy-preview-1594--cfpb-design-system.netlify.app/design-system/patterns/e-mail-signup-forms and compare to https://cfpb.github.io/design-system/patterns/e-mail-signup-forms
There is a very slight difference in the gap between the button and link, but it's 1 or 2 pixels.
Before:
After:
> Refactor email signup to simplify margins and handle different layouts

- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
- packages/cfpb-expandables/src/Summary.js
- packages/cfpb-expandables/src/summary.less
- test/unit-test/src/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.spec.js
- test/unit-test/src/cfpb-expandables/src/Summary-spec.js
Lighthouse is reporting that the `aria-expanded` attribute on the content element of the flyout menu is not correct. 
The trigger should have an `aria-controls` or `aria-owns` property with the ID of the content area they control. However, this means we'd need to add a unique ID pair to each trigger and content. We could do this in the JS using something like https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID, but let's just strip `aria-expanded` off the content to begin with and see how we fair.
- Remove aria-expanded from the content area.
- Refactor Summary component to originate the content fade from the button's `::after`.
1. Should be no visual change.
> Remove aria-expanded from content area

- docs/pages/expandables.md
- test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
Removes whole "variations" section of the expandable. We should not follow this pattern of making arbitrary modifications to expandables. The "expanded" modifier is already covered in the page's second example. The "padded" modifier is covered in the first and subsequent examples on the page (this should probably be merged into the default expandable styles). Text and header elements are covered in the standard examples. `o-expandable_header-left` and `o-expandable_header-right` appear to be unused in the codebase and should be removed.
> Remove "expandables" variations

- packages/cfpb-expandables/src/Summary.js
- packages/cfpb-expandables/src/summary.less
Summaries were incorrectly handling the focusin event, so when links were clicked within the summary component, the focusin fired on them, which clicked the trigger. This could happen even in a suspended state, which was hiding content on clicks of a link.
- Adjust height of Summary content.
- Correctly handle focusin event.
> Bugfix for summary

- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
- packages/cfpb-atomic-component/src/utilities/behavior/behavior.js
- packages/cfpb-expandables/src/Summary.js
https://github.com/cfpb/design-system/pull/1595/ removed the aria-expanded attribute on the flyout content. However, for styling purposes it would be helpful to have some kind of change when the content is expanded or collapsed. We can do this through adding and removing the native `hidden` attribute, however, this shouldn't be added to summaries, which show a truncated view of their content, so are never entirely hidden. Therefore, this PR also adds a `data-open` attribute, which was chosen to follow the `open` attribute that the native `dialog` element uses https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog, as well as the menu example on https://css-tricks.com/the-hidden-attribute-is-visibly-weak/
- Add attributes to flyout content to specify if it's open and/or hidden. …
> Add attributes to flyout content to specify if it's open and/or hidden

- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
FlyoutMenu should not add `hidden` attribute when it is initially open.
- Bugfix for not adding `hidden` attribute when flyout menu is initially open.
1. PR checks should pas..
> FlyoutMenu: Add missing hidden condition

- packages/cfpb-atomic-component/src/utilities/behavior/FlyoutMenu.js
`data-open` was being set `false` after collapsing had completed, but it should happen at the beginning.
- Bugfix: fix order at which data-open closes
> Bugfix: fix order at which data-open closes

- packages/cfpb-layout/src/organisms/email-signup.less
Email signup buttons were getting centered by default, so this sets the text-alignment to inherit.
- Bugfix: Add text alignment to email signup buttons.
> Bugfix: Add text alignment to email signup buttons

- packages/cfpb-typography/src/atoms/links.less
If we explicitly set a `text-align: left` on the jumplinks they won't align to the right by default on right-to-left (RTL) languages. By default in LTR languages it should be aligned left anyway.
- cfpb-typography: Remove text-align: left from `u-block-link`.
1. PR preview in https://cfpb.github.io/design-system/components/lists should be unchanged.
> cfpb-typography: Remove text-align: left from `u-block-link`

- docs/pages/iconography.md
- Break `update` and `updating` icons into two canonical icons
1. Breaks the `update` icon into two rows: the `update` and `updating` icons.
> Break `update` and `updating` icons into two canonical icons

- docs/pages/iconography.md
- packages/cfpb-icons/src/cfpb-icons.less
The round updating icon needs to be included in the animating class.
Follow on to https://github.com/cfpb/design-system/pull/1610
- Add `.cf-icon-svg__updating-round`.
1. Iconography page should have two `updating` animating icons in the table.
> Add `.cf-icon-svg__updating-round`

- docs/admin/src/widgets/StringTrimmed.js
The `StringTrimmed` widget added in https://github.com/cfpb/design-system/pull/543 trimmed onChange, but at some point this led to disallowing spaces to be entered into input fields. This PR adjusts that plugin to work on blur.
- Changes `StringTrimmed` to trim trailing whitespace on blur.
1. Edit any page and enter multiple words in the page title and end with a trailing space or a few. Click out of the field and back into it and see that the trailing spaces are gone. Compare to a production page that won't let you enter multiple words separated by spaces.
> Netlify: Trim inputs on blur instead of change

- docs/assets/css/main-content.less
- docs/pages/iconography.md
- packages/cfpb-icons/usage.md
We want it to be clearer that the icon aliases are not to be used, but still want them for searchability of the page.
- Strikethrough aliases in iconography table
1. PR preview of the iconography table should have strikethrough aliases.
> Strikethrough aliases in iconography table

- docs/pages/expandables.md
- docs/pages/filterable-list-control-panels.md
- docs/special-pages/updating-this-website.md
- packages/cfpb-core/src/utilities.less
- Remove expandable labels and `.u-visually-hidden-on-mobile` class
1. PR preview should show expandables without text labels.
> Remove expandable labels and `.u-visually-hidden-on-mobile` class

- docs/pages/expandables.md
- docs/pages/filterable-list-control-panels.md
- packages/cfpb-expandables/src/Expandable.js
- packages/cfpb-expandables/usage.md
- test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
Doesn't make sense to put a modifier inside the component, it should be a modifier overall on `o-expandable`. This moves the modifier to the component from `content`.
- Move `__onload-open` modifier to the parent component class
1. PR preview expandable should work as before.
> Move `__onload-open` modifier to the parent component class

- docs/pages/expandables.md
- docs/pages/filterable-list-control-panels.md
- docs/special-pages/updating-this-website.md
- packages/cfpb-expandables/usage.md
- test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
- test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
- Convert visually hidden expandable labels to aria-labels
- Remove unused `o-expandable_cue` class.
1. Voicing over the PR preview expandables should still voice show/hide.
`o-expandable_cue` would be useful if you want to target both the open and close cue, but we currently don't target that, and they both have an `o-expandable_link` parent container that could be targeted.
> Convert visually hidden expandable labels to aria-labels

- docs/assets/js/main.js
- docs/pages/summaries.md
- packages/cfpb-expandables/src/SummaryMinimal.js
- packages/cfpb-expandables/src/cfpb-expandables.less
- packages/cfpb-expandables/src/index.js
- packages/cfpb-expandables/src/summary-minimal.less
- packages/cfpb-expandables/src/summary.less
This component is used in the prepaid credit card database, see https://www.consumerfinance.gov/data-research/prepaid-accounts/search-agreements/detail/171172/
It has an existing issue where it appears to have been authored with the intention of having a summary, but it actually doesn't. See [GHE]/CFGOV/platform/issues/3980
- Add Summary Minimal component
1. Visit https://deploy-preview-1634--cfpb-design-system.netlify.app/design-system/components/summaries and view the summary at the bottom of the page.
> Add Summary Minimal component

- docs/pages/buttons.md
The buttons page has jinja code blocks that use code that we don't use anymore.
- Remove inapplicable button jinja snippets
1. PR checks should pass. PR preview buttons page should not have jinja tabs any longer.
> Remove inapplicable button jinja snippets

- docs/pages/expandables.md
- docs/pages/filterable-list-control-panels.md
- docs/special-pages/updating-this-website.md
- packages/cfpb-expandables/src/Expandable.js
- packages/cfpb-expandables/src/expandable.less
- packages/cfpb-expandables/usage.md
- test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
- test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
At one point there was a subtle difference between having `o-expandable_header` and `o-expandable_target`. However, in practice we appear to always use them together, so there is no point in having two separate classes.
Also, the `o-expandable_header-left` and `o-expandable_header-right` appears to be no longer implemented. 
- Remove `o-expandable_target`.
- Remove `o-expandable_header-left`.
- Remove `o-expandable_header-right`.
- Updates docs.
> Remove o-expandable_target, o-expandable_header-left, o-expandable_header-right CSS classes

- packages/cfpb-expandables/src/expandable.less
There are two `o-expandable_header` rules that can be combined. This is a consequence of `o-expandable_target` being removed in https://github.com/cfpb/design-system/pull/1635
- Consolidate `o-expandable_header` rules
1. PR checks should pass. Expandables in PR preview should be unchanged.
> cfpb-expandables: Consolidate `o-expandable_header` rules

- docs/special-pages/updating-this-website.md
Lighthouse checks were failing. This fixes them.
- Add `role="img"` to expandables in updating-this-website.md
> Add `role="img"` to expandables in updating-this-website.md

- packages/cfpb-core/src/utilities.less
We have a utility for showing elements when js is enabled (`.u-js-only`) but the opposite utility [lives in cf.gov](https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/enhancements/utilities.less#L116-L121). This is silly!
I've brought the `.js-is-hidden` utility over here and renamed it to `.u-hide-if-js`, which seems clearer.
> cfpb-core: Pulls in js-is-hidden utility from cf.gov

- test/util/simulate-event.js
This helper wasn't able to set the `key` value on the event after KeyboardEvent instantiation, but it can at the time of instantiation. This PR fixes that.
> Fix simulate-event helper

- docs/pages/iconography.md
- packages/cfpb-icons/src/cfpb-icons.less
Flip certain icons that appear on RTL language pages, which is specifically arabic at this stage.
- Flip specific icons on arabic pages.
1. [In the PR preview](https://deploy-preview-1655--cfpb-design-system.netlify.app/design-system/foundation/iconography), visit the iconography page and see that there is a new RTL column and a check box next to each icon that corresponds to [GHE]/Design-Development/Design-and-Content-Team/issues/176#issuecomment-334258 and that the list of CSS changes in cfpb-icons.less corresponds to the same set.
2. You can simulate the flip by inspecting the page and changing the `<html lang='en'>` tag to `<html lang='ar'>`.
> cfpb-icons: RTL certain icons

- docs/pages/expandables.md
- docs/pages/filterable-list-control-panels.md
- docs/special-pages/updating-this-website.md
- packages/cfpb-expandables/src/expandable.less
- packages/cfpb-expandables/usage.md
- test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
- test/unit-test/src/cfpb-expandables/src/Expandable.spec.js
- Update `o-expandable_link` to more descriptive `o-expandable_cues`
- Add fix to RTL code to target the html lang attribute, like elsewhere where we have RTL targeting CSS. Also, correctly align the cue on RTL pages.
1. PR preview should show an unchanged expandables page.
https://deploy-preview-1659--cfpb-design-system.netlify.app/design-system/components/expandables
vs
https://cfpb.github.io/design-system/components/expandables
> Update `o-expandable_link` to `o-expandable_cues` | RTL fixes

- packages/cfpb-layout/src/organisms/card-group.less
Move CSS from here https://github.com/cfpb/consumerfinance.gov/blob/main/cfgov/unprocessed/css/main.less#L124
- Add `justify-content: center` to cards
1. PR preview cards page should be center aligned.
https://deploy-preview-1660--cfpb-design-system.netlify.app/design-system/patterns/cards
vs
https://cfpb.github.io/design-system/patterns/cards
Before:
After:
> Add `justify-content: center` to cards

- README.md
Travis is no longer used. Remove Travis badge from Readme.
> Remove Travis badge from Readme

- packages/cfpb-layout/src/molecules/card.less
https://github.com/cfpb/design-system/pull/1663 fixed a typo in the less syntax, however, this needs to also exclude the breakout cards so that they don't have their top margin overridden with `auto`.
Also, I noticed that calculations need to be wrapped in parentheses to be applied, otherwise the value ends up as `120px / 2` or whatever, instead of `60px`. 
- cfpb-layout: Fix breakout card margin
1. Check the cards page of the PR preview and compare to the live DS site.
PR preview: https://deploy-preview-1668--cfpb-design-system.netlify.app/design-system/patterns/cards
Live site: https://cfpb.github.io/design-system/patterns/cards
Before:
After:
> cfpb-layout: Fix breakout card margin

- docs/assets/css/grid-demo.less
- docs/pages/grid.md
- docs/pages/variables.md
- packages/cfpb-grid/usage.md
The grid demo was using paragraph tags for its demo labels, which were picking up the max-width we set on paragraphs, so that they weren't extending 100%. This PR changes those tags to be paragraph tags.
Also, we set the `@grid_wrapper-width` variable in code to be 1230px, but referenced it in the docs as 1200px. This PR makes all occurrences show 1230px. 
- Change grid demo label elements to be `<div>`s instead of `<p>`s.
- Update `@grid_wrapper-width` values to be `1230px`.
1. PR preview grid demo page should show grid cells that extend their full area.
Before:
After:
> cfpb-grid: Fix grid demo

- docs/_data/side-navigation.yml
- docs/pages/browse-pages.md
Fix for missing indentation of "Pages" links in Design System sidenav. Taken from Issue 1294:
It's weird that https://cfpb.github.io/design-system/pages/ doesn't have indented links, unlike every other section:
> second level nav missing

- docs/pages/iconography.md
- packages/cfpb-icons/usage.md
We had numerical icons in the source svg folder, but hadn't included them in the DS docs for some reason. 
- Add numerical icons to the docs.
1. The PR preview iconography page should include icons.
> cfpb-icons: Add numerical icons

- packages/cfpb-icons/src/cfpb-icons.less
Align code documentation with the current state of Icons
- Update comment about icon size from 1000x1200 to variable (w) x 19px (h)
> fix: Update explanation of icon height scaling to include the updated SVG height x width

- packages/cfpb-icons/src/cfpb-icons.less
We have dropped support for legacy IE and no longer need to set a max width for our icons. The property causes icons wider than 16px to display smaller than intended.
Fixes https://github.com/cfpb/design-system/issues/1698
- Hard-coded SVG icon maximum width
1. Follow the [reproduction steps](https://github.com/cfpb/design-system/issues/1698) with the [PR preview icon page](https://deploy-preview-1699--cfpb-design-system.netlify.app/design-system/foundation/iconography#icons-with-text). The icons should be 17px wide instead of 16px.
> Remove problematic icon max-width property

- packages/cfpb-forms/src/atoms/text-input.less
**Taken from #1713** 
**The date-picker is not pulling in the placeholder text styling. The placeholder CSS here** https://github.com/cfpb/design-system/blob/main/packages/cfpb-forms/src/atoms/text-input.less#L83 **needs to be updated to apply to the date picker inputs.**
**To Reproduce**
Steps to reproduce the behavior:
1. Go to '[/design-system/components/text-inputs#date-picker-inputs](https://cfpb.github.io/design-system/components/text-inputs#date-picker-inputs)'
2. Look at placeholder text color
3. Compare to [/design-system/components/helper-text#placeholder-text-1](https://cfpb.github.io/design-system/components/helper-text#placeholder-text-1)
**Current Behavior**
Placeholder text in date field is same color as label text (#101820), which is darker than placeholder text (#5a5d61). …
> update date field placeholder text

- packages/cfpb-forms/src/atoms/label.less
**Taken from Bug #1709** 
The live code for the helper text on "[Fieldsets](https://cfpb.github.io/design-system/components/fieldsets)" and "[Helper text](https://cfpb.github.io/design-system/components/helper-text)" pages does not match specs.
NOTE: the [Helper text](http://localhost:4000/design-system/components/helper-text) page is also affected 
**To Reproduce Original Problem:**
1. Navigate to http://localhost:4000/design-system/components/fieldsets
2. Inspect any live code helper text example on the page _(Text is 500 instead of 400 and scales to 14px at mobile)_
**To see CSS fix:**
yarn build
Navigate to and inspect http://localhost:4000/design-system/components/fieldsets
Navigate to and inspect http://localhost:4000/design-system/components/helper-text
Verify font-weight and …
> Update a-label_helper CSS

- docs/pages/buttons.md
- docs/pages/checkboxes.md
- docs/pages/dropdowns.md
- docs/pages/helper-text.md
- docs/pages/radio-buttons.md
- docs/pages/sample-component-page.md
- docs/pages/text-inputs.md
- packages/cfpb-buttons/src/cfpb-buttons.less
- packages/cfpb-forms/src/cfpb-forms.less
**Taken from issue #1702** 
- Text is Avenir Next Regular, 16 px, Gray (#5a5d61)
- Change text to Avenir Next Regular, 16 px, Dark Gray (#43484e)
- Includes: Inline helper, block helper, placeholder text, disabled field text (includes standard and large target checkbox, standard and large target radio button, and dropdown), and pagination
**Navigate to pages:**
1. http://localhost:4000/design-system/components/helper-text
2. http://localhost:4000/design-system/components/checkboxes
3. Verify helper and disabled text color (#5a5d61)
**_switch to branch, yarn build_**
**Navigate to pages:**
1. http://localhost:4000/design-system/components/helper-text
2. http://localhost:4000/design-system/components/checkboxes
3. Verify helper and disabled text color (#43484e)
| Current | Updated |
| …
> Increase Contrast of Helper Text

- docs/pages/text-inputs.md
On the current [text inputs page](https://cfpb.github.io/design-system/components/text-inputs), the disabled input field shows the same value as the other input fields. As a user would not be able to interact with a disabled field, we should display the default placeholder text. 
| Current | After Update |
| -------- | ------------- |
|![Screenshot 2023-09-12 at 6 31 06 PM](https://github.com/cfpb/design-system/assets/130792942/973c276b-9f19-4859-a9ac-082f32e540ac)|![Screenshot 2023-09-12 at 6 29 47 PM](https://github.com/cfpb/design-system/assets/130792942/a42d29fb-810c-44b7-8b75-fefc8b086a75)|
> Swap Default "Value" text with Placeholder Text in Disabled Field

- docs/pages/e-mail-signup-forms.md
- docs/pages/heading-hierarchy.md
- packages/cfpb-typography/src/molecules/slug-header.less
- packages/cfpb-typography/usage.md
`m-slug-header` contained a heavily-customized `a-heading`. It seems like this should be an element of the slug header instead.
- Convert `a-heading` inside `m-slug-header` to `m-slug-header_heading`
1. The "slug heading" on https://deploy-preview-1732--cfpb-design-system.netlify.app/design-system/foundation/headings#slug-heading and https://deploy-preview-1732--cfpb-design-system.netlify.app/design-system/patterns/e-mail-signup-forms should be unchanged.
> Convert `a-heading` inside `m-slug-header` to `m-slug-header_heading`

- docs/pages/heading-hierarchy.md
- packages/cfpb-typography/src/molecules/meta-header.less
- packages/cfpb-typography/usage.md
- Meta header: Adjust margin values to center the pipe and convert units to rems.
1. Compare meta header pipe position on https://deploy-preview-1769--cfpb-design-system.netlify.app/design-system/foundation/headings vs https://cfpb.github.io/design-system/foundation/headings
> Meta header: Adjust margin values

- docs/pages/checkboxes.md
This mismatch is causing the automated Lighthouse tests to fail when run against this repository, for example:
https://github.com/cfpb/design-system/actions/runs/6462905361/job/17545244336
This seems to be due to commit d056169b64b0b228ee3dfc2079327d673e36e3bc. The automated accesslint bot commented on this on the PR (https://github.com/cfpb/design-system/pull/1740#discussion_r1340562961) but this was missed before it got merged in.
> Correct label on large checkbox with helper text

- packages/cfpb-forms/src/organisms/multiselect.less
- test/browser/packages/cfpb-forms.js
Closes #1760
1. Visual inspection
2. Automated tests
- Browsers tests indicate a failure in MS Edge on Windows 10.  I've manually tested in MS Edge (I can't figure out what Windows version I'm remotely connected to) and the Select works as expected.  
|State|UI|
|---|---|
|Default|![default](https://github.com/cfpb/design-system/assets/2592907/591b821e-ac2a-43b7-a23b-f99e3033a004)|
|Focus|![Screenshot 2023-10-12 at 10 29 27 AM](https://github.com/cfpb/design-system/assets/2592907/0ca401e4-3d76-4329-b6ce-b46798a4d331)|
|Hover|![hover](https://github.com/cfpb/design-system/assets/2592907/cab89e35-41a6-45c4-a630-9f5a416a6b7b)|
|Hover/Focus|![hover:focus](https://github.com/cfpb/design-system/assets/2592907/4250e880-fc07-430f-aee9-0616efbf0aa3)| …
> [Tag] Update styles per approved redesign

- packages/cfpb-core/src/base.less
Closes #1782
- Adjust margins for `.lead-paragraph`
- Remove top margin
- Make bottom margin a consistent `15px`
> fix: [Lead paragraph] Adjust margins

- packages/cfpb-forms/src/organisms/multiselect.less
https://github.com/cfpb/design-system/pull/1117 set `display: -webkit-box` to fix an issue with a Chrome v87. Since that time the underlying chromium bug has been closed, and it appears that this property is now causing a more serious issue in Safari. See https://github.com/cfpb/design-system/issues/1728
Fixes https://github.com/cfpb/design-system/issues/1728 
- Remove `display: -webkit-box` property
1. Check the PR preview in Safari and Chrome and see that the multiselect opens the same in both.
Before: 
After:
> Multiselect: Remove `display: -webkit-box` property

- packages/cfpb-forms/src/organisms/multiselect.less
Bug introduced in https://github.com/cfpb/design-system/pull/1777
- Solidifies icon position
- Left-aligns text that wraps
> fix: Multiselect - Deselect icon stays positioned in upper right corner even with multiline text

- docs/pages/text-inputs.md
The lack of placeholder/labels here was failing Lighthouse checks against the design system:
https://github.com/cfpb/design-system/actions/runs/6950964864 https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1700612503369-84118.report.html
This error was introduced in commit 89188d2028821e164ede20324e03f3ab3024301c.
> Add missing placeholder text to text inputs

- docs/pages/alerts.md
- docs/pages/banner-notification.md
- docs/pages/banner-us-gov.md
- docs/pages/buttons.md
- docs/pages/checkboxes.md
- docs/pages/date-picker.md
- docs/pages/fieldsets.md
- docs/pages/helper-text.md
- docs/pages/heroes.md
- docs/pages/links.md
- docs/pages/pagination.md
- docs/pages/radio-buttons.md
- docs/pages/selects.md
- docs/pages/tables.md
- docs/pages/taglines.md
- docs/pages/text-inputs.md
- docs/pages/text-introductions.md
- docs/pages/typography.md
- docs/pages/video.md
- docs/pages/wells.md
- packages/cfpb-atomic-component/src/utilities/atomic-helpers.js
- packages/cfpb-forms/src/organisms/Multiselect.js
- packages/cfpb-forms/src/organisms/MultiselectModel.js
- packages/cfpb-forms/src/organisms/multiselect.less
- test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
- test/unit-test/src/cfpb-forms/src/organisms/Multiselect.spec.js
These changes are in support of development for `design-system-react`.  In order to integrate the DS Multiselect into our React implementation, we need to be able to apply configuration for: 
- Max number of selections (number)
- Should display Tag/Pill (boolean)
- feat: Support configuration options for Atomic components
- feat: [Mulitselect] Make rendering of selected Tags configurable
- feat: [Multiselect] Make maximum number of selections configurable
- Should we support configuration per-Multiselect when calling `instantiateAll()`? Currently it takes a single configuration object but this could be updated to accept an array of configurations. 
In parallel I'm integrating this component into the Design System React and these proposed changes are working great!
> Multiselect: Enable configuration at instantiation

- docs/assets/css/color-swatches.less
Table headers on the [DS Tables](https://cfpb.github.io/design-system/components/tables) page are incorrectly width-restricted due to styles defined in `color-swatches.less`. This PR restricts the application of that width to `.swatch th`.
- [Tables - Preview deployment](https://deploy-preview-1835--cfpb-design-system.netlify.app/design-system/components/tables)
|Before|After|
|---|---|
|<img width="1167" alt="Screenshot 2023-11-16 at 9 43 59 AM" src="https://github.com/cfpb/design-system/assets/2592907/43119c90-380f-4bdf-8efc-5f921475c3f7">|<img width="1167" alt="Screenshot 2023-11-16 at 9 44 15 AM" src="https://github.com/cfpb/design-system/assets/2592907/6a4ac5bd-e09d-443d-bd28-2be5c03f35ab">|
> fix: Avoid style bleed for <th> between Colors and Tables pages

- test/browser/docs/show-details.js
This test was flaky, this aligns the syntax with the test above it.
> Adjust test negation statement

- docs/search-results.html
This was failing lighthouse because the skip link didn't have a target.
- Add id and role to search results main element
1. Lighthouse should pass tonight.
> Add id and role to search results main element

- packages/cfpb-expandables/src/expandable.less
The selector is `.o-expandable_cues`, not `.o-expandable_header_cues`
- cfpb-expandables: Fix incorrect selector target
1. Visit the expandables preview page and edit the html element to have the value `ar` instead of `en`. Add `dir="rtl"` to the main element. The cues should then be left-aligned.
> cfpb-expandables: Fix incorrect selector target

- esbuild/docs/build.js
- esbuild/packages/build.js
- packages/cfpb-typography/src/licensed-fonts.less
- scripts/fonts.sh
WOFF files are only for IE11. We can probably get rid of them at this point https://caniuse.com/woff2
- Remove older WOFF files
> cfpb-typography: Remove older WOFF files

- docs/pages/iconography.md
- packages/cfpb-forms/src/atoms/select.less
- packages/cfpb-forms/src/molecules/form-fields.less
- packages/cfpb-icons/src/cfpb-icons.less
- packages/cfpb-icons/src/icons-svg-inline.cjs
The inline SVG helper can be passed a color value to fill an inline SVG with any color that is desired. This depends on the Less utilities `red(…)`, `green(…)`, and `blue(…)` to pick out the color channels of the passed in color. While this is a flexible approach that would allow coloring the icons any color we want, in practice we currently only use this to color the icons gray or black. If and when we move to Sass the color channel utilities would need to be migrated to Sass equivalents (as will the whole inline SVG plugin). The color channel utilities also only currently take Less variables for colors, and not CSS properties (custom variables).
With all that in mind, this PR simplifies the inline SVG utility so that the arbitrary color argument is replaced with a boolean flag for …
> cfpb-icons: Change inline SVG fill color argument to grayscale boolean flag

- packages/cfpb-expandables/usage.md
- test/unit-test/src/cfpb-atomic-component/src/utilities/atomic-helpers.spec.js
Some docs cleanup from https://github.com/cfpb/design-system/pull/1924 to remove unneeded `o-expandable__padded` references.
- Remove `o-expandable__padded` from docs
> Remove `o-expandable__padded` from docs

- packages/cfpb-core/src/base.less
- packages/cfpb-typography/src/atoms/date.less
- packages/cfpb-typography/src/molecules/pull-quote.less
This argument for `heading-5(…)` and `heading-6(…)` does not to be anything more than an argument. There doesn't appear to be an implementation.
- Remove unused `@text-shadow` argument
> Remove unused `@text-shadow` argument

- scripts/update-gh-pages.sh
Fixes https://github.com/cfpb/design-system/issues/1941
https://github.com/cfpb/design-system/pull/1909 changed the `build` command to only build the documentation assets, however, the old command included `bundle exec jekyll build`. The `update-gh-pages.sh` script should have been updated to use the `build-netlify` command instead, which includes jekyll building. Without that it was building the assets, but not the pages.
- Change `update-gh-pages.sh`  to use `yarn build-netlify` instead of `yarn build`.
1. PR checks should pass. I think we just need to merge it and see.
> Update `update-gh-pages.sh` to fix production not updating

- packages/cfpb-notifications/src/molecules/notification.less
Fixes https://github.com/cfpb/design-system/issues/1943
The standard link color on a red background in the alert notifications is not accessible.
- cfpb-notification: Add color contrast safe colors for links in an error notification
1. PR checks should pass. Visit the alert page in the PR preview and run Google Lighthouse and it should pass the accessibility check with 100%.
> cfpb-notification: Add color contrast safe colors for links in an error notification

- docs/pages/alerts.md
- packages/cfpb-notifications/src/molecules/notification.less
- Add links to different alert notifications docs
- Make all alerts have the same accessible color values.
1. See alerts page on the PR preview. The different alert types will have links in them.
> cfpb-notifications: Add links to different alerts

- docs/_includes/search-scripts.html
- docs/assets/css/search.less
- test/cypress/e2e/docs/search.cy.js
Search broke at some point because embedded SVG icons were messing up the quoting of the search string. 
- Properly escape search string data.
- Add cypress test for search.
- Left align search results and cfpb logo.
1. http://localhost:4000/design-system/search/ should work for searching.
> Fix search

- docs/pages/alerts.md
- docs/pages/checkboxes.md
- docs/pages/fieldsets.md
- docs/pages/labels.md
- docs/pages/selects.md
- packages/cfpb-forms/src/molecules/form-fields.less
- packages/cfpb-forms/usage.md
cfgov PR https://github.com/cfpb/consumerfinance.gov/pull/8384
- Unstyled `m-form-field__select`, `m-form-field__success`, `m-form-field__warning`, `m-form-field__error`
- Update `m-form-field--checkbox--success` to `m-form-field--checkbox-success`.
- Update `m-form-field--checkbox--warning` to `m-form-field--checkbox-warning`.
- Update `m-form-field--checkbox--error` to `m-form-field--checkbox-error`.
> Remove/update m-form-field modifiers

- docs/pages/text-inputs.md
- packages/cfpb-forms/src/atoms/text-input.less
https://github.com/cfpb/design-system/pull/1886 erroneously set the `a-text-input` error/warning/success modifiers to be blocks, apparently because of a mistake I made reconciling conflicts in https://github.com/cfpb/design-system/pull/1886/commits/6f6bbbbc307f1e5dccc7e6b8f9a90fa196743294 
https://github.com/cfpb/design-system/pull/1983/ updated the example to follow the CSS, but the CSS should actually be updated to retain these as modifiers instead of erroneously as blocks.
- Fix `a-text-input` error/warning/success modifiers
1. Text inputs should have error/warning/success colored border styling on https://deploy-preview-1984--cfpb-design-system.netlify.app/design-system/components/text-inputs
> Fix `a-text-input` error/warning/success modifiers

- docs/pages/integrating-the-design-system-into-your-project.md
npmcdn.com was moved to unpkg.com in 2016, see:
https://x.com/mjackson/status/770424625754939394
https://github.com/mjackson/unpkg/commit/ea0fd214c2073a4a5474ffb1e3c7dc1bff839a88
The link redirects, but we should point to the right domain.
> Link to unpkg.com instead of npmcdn.com

- docs/pages/featured-content-modules.md
- docs/pages/links.md
- packages/cfpb-layout/usage.md
- packages/cfpb-typography/src/atoms/links.less
- packages/cfpb-typography/usage.md
Jump links required both the `a-link--jump` and `a-link--icon-after-text` (or `a-link--icon-before-text`) modifiers to correctly layout with an icon. However, using flexbox we can have these links correctly layout whether or not they have an icon and whether or not it's on the left or right-hand side.
- Remove `a-link--icon-before-text` and `a-link--icon-after-text`
- Convert Jump Links to use flexbox.
1. Visit https://deploy-preview-1987--cfpb-design-system.netlify.app/design-system/components/links and check out the jump links across screen sizes.
> Remove `a-link--icon-before-text` and `a-link--icon-after-text`

- docs/pages/links.md
- packages/cfpb-typography/src/atoms/links.less
- packages/cfpb-typography/src/molecules/list.less
- Update jump links to handle external icons and only right-align right arrows.
1. Jump links on https://deploy-preview-1988--cfpb-design-system.netlify.app/design-system/components/links have a jump links with external links.
> Update jump links to handle external icons

- packages/cfpb-typography/src/atoms/links.less
https://github.com/cfpb/design-system/pull/1989 removed `a-link--icon`, but that means the underline goes right under the icon. This PR makes `a-link`, but default run the underline only under the text, and not an accompanying icon.
- Set underline on link by default
1. https://deploy-preview-1990--cfpb-design-system.netlify.app/design-system/components/links#link-with-icon should not have a line under the icon.
> Set underline on link by default

- docs/pages/links.md
- packages/cfpb-typography/src/atoms/links.less
- Add `flex-shrink` to prevent squeezing of icon on long jump link text.
1. Visit links example page and resize to mobile and see long jump link does not crush the accompanying icon.
Before:
After:
> Prevent squeezing of icon on long jump link text

- packages/cfpb-atomic-component/src/cfpb-atomic-component.less
- packages/cfpb-atomic-component/src/utilities/transition/transition.less
https://github.com/cfpb/consumerfinance.gov/pull/8514 should have retained all the Less files, but accidentally deleted the ones in the cfpb-atomic-component package. Thanks for catching this @chosak 
- Re-add cfpb-atomic-component missing Less files
> Re-add cfpb-atomic-component missing Less files

- docs/pages/alerts.md
- docs/pages/banner-notification.md
- docs/pages/text-introductions.md
- docs/pages/wells.md
- packages/cfpb-notifications/usage.md
- packages/cfpb-typography/usage.md
Jump links without the `a-link__text` class do not get an underline, and should (aside from the DS sidebar links).
- Add missing `a-link__text` class to jump links
1. Check the banner page in the PR preview and see that the links have underlines.
Before:
After:
> Add `a-link__text` class to jump links

- packages/cfpb-design-system/src/components/cfpb-notifications/banner.scss
- Update banner color scheme to change the background color to `teal-dark` instead of `teal-mid-dark` and change the visited color to `teal-40`.
1. Visit banner page on PR preview https://deploy-preview-2014--cfpb-design-system.netlify.app/design-system/components/banner-notification
Visited link is the first link, whereas unvisted link is not visited (sorry, I should I visited the second link to align with the text).
> Update banner color scheme

- docs/pages/variables.md
Update the font docs to reflect changes in https://github.com/cfpb/design-system/pull/2005
- Update font docs
> Update font docs

- docs/pages/tags.md
- packages/cfpb-design-system/src/components/cfpb-forms/index.js
- packages/cfpb-design-system/src/components/cfpb-forms/tag.scss
- Tags: Add initial tag styling
1. Check the tags page at https://deploy-preview-2026--cfpb-design-system.netlify.app/design-system/components/tags
> Tags: Add initial tag styling

- docs/pages/tags.md
An empty link on this page is causing the Lighthouse tests to fail:
https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1724718029743-49279.report.html
> Remove empty link from tags page

- packages/cfpb-design-system/src/abstracts/heading-mixins.scss
- packages/cfpb-design-system/src/components/cfpb-typography/slug-header.scss
The heading mixins allow passing in a font-size override that is not used in the wild. There is also a `$font-size` variable that abstracts the `$size-*` variables. 
- Remove `$fs` argument from `heading-*` mixins.
- Remove `$font-size` variable.
1. The heading examples should not be changed.
https://deploy-preview-2027--cfpb-design-system.netlify.app/design-system/foundation/headings
vs
https://cfpb.github.io/design-system/foundation/headings
> Remove `$font-size` variable

- docs/assets/css/code.scss
- docs/pages/expandables.md
- docs/pages/grid.md
- docs/pages/helper-classes-mixins.md
- docs/pages/media-queries.md
- docs/pages/transition-patterns.md
Code syntax highlighting had some contrast errors. This PR (hopefully) fixes them.
- Fix syntax highlighting a11y failures
1. Easiest is to probably merge this and see how lighthouse does tonight.
> Fix syntax highlighting a11y failures

- .github/workflows/lighthouse.yml
The `set-output` command used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of ::set-output to "$GITHUB_OUTPUT"
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
- Lighthouse: Use envvar instead of set-output command
1. Will need to merge and let this run over night.
> Lighthouse: Use envvar instead of set-output command

- package.json
- scripts/cypress.sh
- Update Cypress command to match that in cfgov.
1. `yarn cy` should run Cypress.
2. `yarn cy open` should open Cypress.
> Update Cypress command

- .github/workflows/lighthouse.yml
Yarn 4 doesn't have a `yarn cache dir` command. We also have the global cache turned off. This PR updates the lighthouse GH action to use the literal cache directory path.
- Lighthouse action: Update yarn cache path
1. We'll need to merge and see how this runs tonight.
> Lighthouse action: Update yarn cache path

- .github/workflows/lighthouse.yml
- Add `on: workflow_dispatch:` to allow manually triggering of Lighthouse job
1.  After merging, should allow manually running of the lighthouse action from the actions GH tab.
> Add `on: workflow_dispatch:` to allow manually triggering of Lighthouse job

- .github/workflows/lighthouse.yml
A nightly GitHub Action runs Lighthouse against the Design System documentation site, to ensure that it meets with accessibility guidelines.
Currently this Action is generating a warning message, [for example](https://github.com/cfpb/design-system/actions/runs/11524988694):
> No files were found with the provided path: .lighthouseci. No artifacts will be uploaded.
This warning occurs because the upload step can't find the Lighthouse results.
We don't actually use the raw Lighthouse results in any way; as part of the nightly test, HTML reports are uploaded to temporary Google storage and their public URLs are included in the Action log.
Thus there's no need to upload the raw run results. This commit removes the upload step, thus fixing the warning.
> Remove unused Lighthouse results upload

- docs/pages/helper-classes-mixins.md
- packages/cfpb-design-system/src/utilities/utilities.scss
This class is used in TCCP.
- Add `u-small-text--subtle` modifier for making gray small text.
1. There should be mention of the modifier in the docs at https://deploy-preview-2097--cfpb-design-system.netlify.app/design-system/development/helper-classes-and-mixins
> Add `u-small-text--subtle`

- packages/cfpb-design-system/src/utilities/behavior/behavior.js
- packages/cfpb-design-system/src/utilities/index.js
- Remove behavior remove method, which was unused and was just a wrapper around removeEventListener.
- Update behavior method names
> Update behavior method names

- packages/cfpb-design-system/src/components/cfpb-buttons/button.scss
If the width of the buttons is set by a parent container, such as is done in https://www.consumerfinance.gov/paying-for-college/your-financial-path-to-graduation/, then the button text will be left-aligned by default. This makes it so it is center aligned.
- Buttons: add `justify-content: center`
1. Visit the buttons preview page and inspect the buttons. Manually set their width to 100% and see that the text is centered in the button.
> Buttons: add `justify-content: center`

- docs/pages/filterable-list-control-panels.md
Filter buttons should appear in a group as the sole parent.
- Fix filter button group to move group to its own container.
1. Filterable list control panels page should not have a broken filter button group.
Before:
After:
> Fix filter button group

- packages/cfpb-design-system/src/components/cfpb-layout/hero.scss
- Update hero text margin to `auto 0`.
- Minor formatting of hero SCSS to align with newlines used between rules elsewhere.
1. Visit the PR preview heroes page and see that a short hero heading text doesn't get centered at desktop sizes. https://deploy-preview-2127--cfpb-design-system.netlify.app/design-system/patterns/heroes
> Update hero text margin to `auto 0`

- CONTRIBUTING.md
> Update release documentation

- packages/cfpb-design-system/package.json
One piece of fallout from https://github.com/cfpb/design-system/commit/005bce900a9652fff77c746c108e05b5a9a778ab is that the way code is imported by dependent js is actually quite different. With an `exports` key provided, **only** those exports are allowed rather than falling back to walking the filesystem (which we do a bunch in cf.gov).
This provides an `icons` export so that icons can be imported into js (which will need to be updated in dependent projects, namely cfgov, from existing `@cfpb/cfpb-design-system/src/components/cfpb-icons/icons/<icon.svg>` style imports. I'll do this for cfgov once this PR is merged and a release created (along with changes to js imports which 005bce9 also requires).
> Provide icon exports

- packages/cfpb-design-system/src/components/cfpb-tooltips/index.js
Some consumers of these tooltips may need access to the underlying tippy object to, eg, check the tooltip state, etc.
This PR provides the initialized tippy object as a `tooltip` key on the initialized component instance (this key is null before initialization).
> Provide instantiated tooltip object on initialized component

- packages/cfpb-design-system/src/components/cfpb-notifications/notification.scss
Notification content should wrap if it gets too wide.
- Notifications: Set max-width of content.
1. Check PR preview for the alerts page and edit the notification text to be really long and see that it wraps before the width of the notification background/border.
> Notifications: Set max-width of content

- docs/_data/side-navigation.yml
- docs/_includes/examples/buttons.html
- docs/_includes/examples/checkboxes-large-with-helper.html
- docs/_includes/examples/checkboxes-large.html
- docs/_includes/examples/checkboxes.html
- docs/_includes/examples/multiselects.html
- docs/_includes/examples/radio-buttons-large-with-helper.html
- docs/_includes/examples/radio-buttons-large.html
- docs/_includes/examples/radio-buttons-with-helper.html
- docs/_includes/examples/radio-buttons.html
- docs/_includes/examples/selects.html
- docs/_includes/examples/text-inputs.html
- docs/_includes/variation-content.html
- docs/pages/buttons.md
- docs/pages/checkboxes.md
- docs/pages/radio-buttons.md
- docs/pages/reference-for-component-states.md
- docs/pages/selects.md
- docs/pages/text-inputs.md
Adds initial component reference page and moves components that show multiple states from their component pages to the reference page.
- Add component reference page
1. See https://deploy-preview-2236--cfpb-design-system.netlify.app/design-system/development/reference-for-component-states and individual component pages to see that "states" have been moved to the reference sheet.
- Additional component examples can be moved over. I just moved the existing "states" examples over for now.
> Add component reference page

- docs/_includes/examples/buttons.html
- docs/_includes/examples/checkboxes.html
- docs/_includes/examples/radio-buttons-with-helper.html
- docs/_includes/examples/radio-buttons.html
- docs/_includes/examples/text-inputs.html
- docs/pages/info-unit-groups-link-blobs.md
See recent Lighthouse test failures [here](https://github.com/cfpb/design-system/actions/runs/15101356615/job/42442649151).
- Missing "Related Items" links at the bottom of https://cfpb.github.io/design-system/patterns/info-unit-groups.
- Invalid heading hierarchy on https://cfpb.github.io/design-system/development/reference-for-component-states.
> Fix Lighthouse a11y failures on two pages

- packages/cfpb-design-system/src/utilities/utilities.scss
The `u-show-on-mobile` utility sets `display: block`, which can break some elements that use flexbox. This PR makes it so that it only hides the element.
- Refactor `u-show-on-mobile` to not force display state when visible.
> Refactor `u-show-on-mobile` to not force display state when visible

- packages/cfpb-design-system/src/abstracts/vars.scss
- packages/cfpb-design-system/src/components/cfpb-forms/form-alert.scss
- Migrate form alert variables to CSS custom properties.
1. Check the reference page and see that the form field-level alerts are unchanged in their coloration. 
https://deploy-preview-2286--cfpb-design-system.netlify.app/design-system/development/reference-for-component-states#field-level-alert
> Migrate form alert variables to CSS custom properties

- docs/pages/helper-classes-mixins.md
- packages/cfpb-design-system/src/utilities/utilities.scss
I couldn't find a use for `u-link-border` mixin, so removed it.
- Update outdated u-link and u-small-text utility syntax in docs.
- Remove unused `u-link-border` mixin.
- Remove unused `u-link__hover-child` mixin.
1. See updated docs in https://deploy-preview-2307--cfpb-design-system.netlify.app/design-system/development/helper-classes-and-mixins
> Update outdated SASS utility syntax in docs | remove unused mixins
